# Generated by Django 5.2 on 2026-08-15 15:02

import core.models.base
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employeerole_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('target_type', models.CharField(choices=[('SALES_AMOUNT', 'إجمالي المبيعات'), ('NET_SALES', 'صافي المبيعات بعد المرتجعات'), ('GROSS_PROFIT', 'مجمل الربح'), ('ORDER_COUNT', 'عدد الطلبات'), ('CUSTOMER_COUNT', 'عدد العملاء النشطين')], db_index=True, default='NET_SALES', max_length=24, verbose_name='نوع الهدف')),
                ('target_value', models.DecimalField(decimal_places=2, help_text='مبلغ للأنواع المالية · عدد صحيح لما عداها', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='قيمة الهدف')),
                ('minimum_achievement_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='الحد الأدنى للتحقيق ٪')),
                ('status', models.CharField(choices=[('DRAFT', 'مسوّدة'), ('ACTIVE', 'نشط'), ('CLOSED', 'مقفل')], db_index=True, default='DRAFT', max_length=16, verbose_name='الحالة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('achieved_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المُحقَّق')),
                ('achievement_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة التحقيق ٪')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإقفال')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_targets', to=settings.AUTH_USER_MODEL, verbose_name='أقفله')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='employees.employeeprofile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'هدف شهري',
                'verbose_name_plural': 'الأهداف الشهرية',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month', 'status'], name='targets_mon_year_21350f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee', 'year', 'month'), name='one_target_per_employee_month')],
            },
        ),
    ]
