# Generated by Django 5.2 on 2026-08-13 04:05

import core.models.base
import core.models.translatable
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='الكود')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('kind', models.CharField(choices=[('PERCENTAGE', 'نسبة مئوية'), ('FIXED', 'مبلغ ثابت'), ('FREE_SHIPPING', 'شحن مجاني')], max_length=16, verbose_name='النوع')),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='نسبة أو مبلغ حسب النوع · تُتجاهَل للشحن المجاني', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='القيمة')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='للنسبة المئوية — يمنع خصمًا ضخمًا على طلب كبير', max_digits=12, null=True, verbose_name='سقف الخصم')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الحد الأدنى للطلب')),
                ('account_types', models.JSONField(blank=True, default=list, help_text='فارغ = الجميع', verbose_name='أنواع الحسابات')),
                ('first_order_only', models.BooleanField(default=False, verbose_name='للطلب الأول فقط')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد الاستخدام الكلي')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, verbose_name='حد الاستخدام لكل عميل')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='عدد الاستخدامات')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='يبدأ في')),
                ('ends_at', models.DateTimeField(blank=True, help_text='فارغ = بلا نهاية', null=True, verbose_name='ينتهي في')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
                ('categories', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.category', verbose_name='فئات محددة')),
                ('products', models.ManyToManyField(blank=True, help_text='فارغ = كل المنتجات', related_name='coupons', to='catalog.product', verbose_name='منتجات محددة')),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'الكوبونات',
                'ordering': ['-created_at'],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الخصم')),
                ('order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الطلب')),
                ('reference_type', models.CharField(blank=True, max_length=32, verbose_name='نوع المرجع')),
                ('reference_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف المرجع')),
                ('is_cancelled', models.BooleanField(default=False, help_text='الطلب أُلغي — الاستخدام لا يُحتسب لكن السجل يبقى', verbose_name='ملغى')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.coupon', verbose_name='الكوبون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'استخدام كوبون',
                'verbose_name_plural': 'استخدامات الكوبونات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='promotions__is_acti_2ec57c_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'user'], name='promotions__coupon__00bce9_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['reference_type', 'reference_id'], name='promotions__referen_65b070_idx'),
        ),
    ]
