# Generated by Django 5.2 on 2026-08-16 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='فارغ = حملة عامة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_coupons', to=settings.AUTH_USER_MODEL, verbose_name='مالك الكوبون'),
        ),
    ]
