# Generated by Django 5.2 on 2026-08-13 05:40

import core.models.base
import core.models.translatable
import django.core.validators
import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('code', models.SlugField(unique=True, verbose_name='الرمز')),
                ('adapter_key', models.CharField(help_text='اسم المحوّل المسجّل في الكود', max_length=50, verbose_name='مفتاح المحوّل')),
                ('supported_methods', models.JSONField(default=list, help_text='قائمة من PaymentMethodKind', verbose_name='طرق الدفع المدعومة')),
                ('supported_currencies', models.JSONField(default=list, help_text='فارغ = كل العملات', verbose_name='العملات المدعومة')),
                ('supported_channels', models.JSONField(default=list, help_text='ONLINE · POS · EMPLOYEE — فارغ = الكل', verbose_name='القنوات المسموحة')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الحد الأدنى')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الحد الأقصى')),
                ('priority', models.IntegerField(default=0, help_text='الأعلى يُجرَّب أولًا', verbose_name='الأولوية')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='وضع تجريبي')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'بوابة دفع',
                'verbose_name_plural': 'بوابات الدفع',
                'ordering': ['-priority', 'code'],
                'indexes': [models.Index(fields=['is_active', '-priority'], name='payments_pa_is_acti_b2b997_idx')],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('reference', models.CharField(db_index=True, default=payments.models.transaction_reference, max_length=32, unique=True, verbose_name='المرجع')),
                ('method', models.CharField(choices=[('COD', 'دفع عند الاستلام'), ('CASH', 'نقدي'), ('CARD', 'بطاقة'), ('WALLET', 'محفظة إلكترونية'), ('BANK', 'تحويل بنكي'), ('INSTALLMENT', 'تقسيط')], max_length=16, verbose_name='طريقة الدفع')),
                ('reference_type', models.CharField(blank=True, max_length=32, verbose_name='نوع المرجع')),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='معرّف المرجع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('currency', models.CharField(choices=[('EGP', 'جنيه مصري'), ('USD', 'دولار أمريكي'), ('EUR', 'يورو'), ('SAR', 'ريال سعودي'), ('AED', 'درهم إماراتي')], default='EGP', max_length=3, verbose_name='العملة')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المعالجة'), ('AUTHORIZED', 'مُصرَّح'), ('CAPTURED', 'مُحصَّل'), ('FAILED', 'فشل'), ('CANCELLED', 'ملغى'), ('REFUNDED', 'مسترد')], db_index=True, default='PENDING', max_length=16, verbose_name='الحالة')),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='مرجع البوابة')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='استجابة البوابة')),
                ('failure_code', models.CharField(blank=True, max_length=100, verbose_name='كود الفشل')),
                ('failure_message', models.TextField(blank=True, verbose_name='رسالة الفشل')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='مفتاح المنع التكراري')),
                ('authorized_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التصريح')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التحصيل')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='customers.customerprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymentprovider', verbose_name='البوابة')),
            ],
            options={
                'verbose_name': 'معاملة دفع',
                'verbose_name_plural': 'معاملات الدفع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('key', models.CharField(max_length=100, verbose_name='المفتاح')),
                ('value', models.TextField(help_text='مشفّرة — لا تُقرأ عبر الـ API', verbose_name='القيمة')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='للوضع التجريبي')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='payments.paymentprovider', verbose_name='البوابة')),
            ],
            options={
                'verbose_name': 'بيانات اعتماد بوابة',
                'verbose_name_plural': 'بيانات اعتماد البوابات',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('reference', models.CharField(default=payments.models.refund_reference, max_length=32, unique=True, verbose_name='المرجع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المعالجة'), ('COMPLETED', 'مكتمل'), ('FAILED', 'فشل')], db_index=True, default='PENDING', max_length=16, verbose_name='الحالة')),
                ('provider_reference', models.CharField(blank=True, max_length=200, verbose_name='مرجع البوابة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإكمال')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymenttransaction', verbose_name='المعاملة الأصلية')),
            ],
            options={
                'verbose_name': 'استرداد',
                'verbose_name_plural': 'الاستردادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='من البوابة — يمنع المعالجة المكررة', max_length=200, verbose_name='معرّف الحدث')),
                ('event_type', models.CharField(max_length=100, verbose_name='نوع الحدث')),
                ('payload', models.JSONField(default=dict, verbose_name='الحمولة')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='التوقيع صالح')),
                ('is_processed', models.BooleanField(db_index=True, default=False, verbose_name='عولج')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المعالجة')),
                ('processing_error', models.TextField(blank=True, verbose_name='خطأ المعالجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الاستقبال')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='payments.paymentprovider')),
            ],
            options={
                'verbose_name': 'حدث بوابة',
                'verbose_name_plural': 'أحداث البوابات',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='payments_pa_referen_30b483_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_a2ce56_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', '-created_at'], name='payments_pa_provide_876306_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('idempotency_key__gt', '')), fields=('idempotency_key',), name='unique_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='providercredential',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('provider', 'key', 'is_sandbox'), name='unique_provider_credential'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_webhook_event'),
        ),
    ]
