# Generated by Django 5.2 on 2026-08-15 16:05

import core.models.base
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import suppliers.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0002_alter_stockmovement_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='مسؤول التواصل')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=0, verbose_name='مهلة السداد (يوم)')),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0, verbose_name='مهلة التوريد (يوم)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
            ],
            options={
                'verbose_name': 'مورّد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('number', models.CharField(default=suppliers.models.purchase_order_number, editable=False, max_length=24, unique=True, verbose_name='رقم الأمر')),
                ('status', models.CharField(choices=[('DRAFT', 'مسوّدة'), ('SENT', 'مُرسَل'), ('PARTIAL', 'استلام جزئي'), ('RECEIVED', 'مستلَم بالكامل'), ('CANCELLED', 'ملغى')], db_index=True, default='DRAFT', max_length=16, verbose_name='الحالة')),
                ('expected_on', models.DateField(blank=True, null=True, verbose_name='التاريخ المتوقَّع')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستلام الكامل')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الإجمالي')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.stocklocation', verbose_name='موقع الاستلام')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier', verbose_name='المورّد')),
            ],
            options={
                'verbose_name': 'أمر شراء',
                'verbose_name_plural': 'أوامر الشراء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('quantity_ordered', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المطلوبة')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='الكمية المستلمة')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر الوحدة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='suppliers.purchaseorder', verbose_name='الأمر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'سطر أمر شراء',
                'verbose_name_plural': 'أسطر أوامر الشراء',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('kind', models.CharField(choices=[('INVOICE', 'فاتورة مورّد'), ('PAYMENT', 'سداد له'), ('CREDIT_NOTE', 'إشعار دائن — مرتجع له'), ('ADJUSTMENT', 'تسوية')], db_index=True, max_length=16, verbose_name='النوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ')),
                ('occurred_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('due_on', models.DateField(blank=True, null=True, verbose_name='الاستحقاق')),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='المرجع')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='suppliers.purchaseorder', verbose_name='أمر الشراء')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_supplier_entries', to=settings.AUTH_USER_MODEL, verbose_name='سجّلها')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='suppliers.supplier', verbose_name='المورّد')),
            ],
            options={
                'verbose_name': 'حركة حساب مورّد',
                'verbose_name_plural': 'حركات حسابات الموردين',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('supplier_sku', models.CharField(blank=True, max_length=64, verbose_name='رمز المورّد')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر الشراء')),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى للطلب')),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0, verbose_name='مهلة التوريد (يوم)')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='المورّد المفضَّل')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='متاح')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offers', to='catalog.product', verbose_name='المنتج')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='suppliers.supplier', verbose_name='المورّد')),
            ],
            options={
                'verbose_name': 'عرض مورّد',
                'verbose_name_plural': 'عروض الموردين',
                'ordering': ['product', 'unit_cost'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='suppliers_p_supplie_5be0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierledgerentry',
            index=models.Index(fields=['supplier', '-occurred_on'], name='suppliers_s_supplie_45b487_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('purchase_order__isnull', False)), fields=('purchase_order', 'kind'), name='unique_supplier_entry_per_order_kind'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('supplier', 'product'), name='unique_offer_per_supplier_product'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_preferred', True)), fields=('product',), name='one_preferred_supplier_per_product'),
        ),
    ]
