# Generated by Django 5.2 on 2026-08-16 13:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='list_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر العرض وقت الإنشاء'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='quantity_returned',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية المرتجعة'),
        ),
    ]
