# Generated by Django 5.2 on 2026-08-17 23:45

import core.encryption
import core.models.base
import core.models.translatable
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.SlugField(unique=True, verbose_name='الرمز')),
                ('label_ar', models.CharField(max_length=120, verbose_name='الاسم بالعربية')),
                ('label_en', models.CharField(max_length=120, verbose_name='الاسم بالإنجليزية')),
                ('direction', models.CharField(choices=[('OUT', 'صادر'), ('IN', 'وارد'), ('BOTH', 'صادر ووارد')], db_index=True, default='OUT', max_length=8, verbose_name='الاتجاه')),
                ('transport', models.CharField(choices=[('SMTP', 'SMTP'), ('CONSOLE', 'طرفية — يُسجَّل ولا يُرسَل')], default='SMTP', max_length=16, verbose_name='المحوّل')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='الخادم')),
                ('port', models.PositiveIntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='المنفذ')),
                ('security', models.CharField(choices=[('NONE', 'بلا تأمين'), ('TLS', 'STARTTLS'), ('SSL', 'SSL/TLS')], default='TLS', max_length=8, verbose_name='التأمين')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='اسم المستخدم')),
                ('timeout', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='المهلة (ثانية)')),
                ('from_email', models.EmailField(max_length=254, verbose_name='المرسل')),
                ('from_name_ar', models.CharField(blank=True, max_length=120, verbose_name='اسم المرسل بالعربية')),
                ('from_name_en', models.CharField(blank=True, max_length=120, verbose_name='اسم المرسل بالإنجليزية')),
                ('reply_to', models.EmailField(blank=True, max_length=254, verbose_name='الردّ إلى')),
                ('imap_host', models.CharField(blank=True, max_length=255, verbose_name='خادم IMAP')),
                ('imap_port', models.PositiveIntegerField(default=993, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='منفذ IMAP')),
                ('imap_security', models.CharField(choices=[('NONE', 'بلا تأمين'), ('TLS', 'STARTTLS'), ('SSL', 'SSL/TLS')], default='SSL', max_length=8, verbose_name='تأمين IMAP')),
                ('imap_username', models.CharField(blank=True, max_length=255, verbose_name='مستخدم IMAP')),
                ('imap_folder', models.CharField(default='INBOX', max_length=100, verbose_name='المجلد')),
                ('imap_last_uid', models.BigIntegerField(default=0, verbose_name='آخر معرّف مسحوب')),
                ('is_marketing', models.BooleanField(default=False, help_text='لا تُسنَد إليه رسائل الحساب والأمان — القوائم السوداء تصيبه أولًا', verbose_name='حساب تسويقي')),
                ('is_default', models.BooleanField(default=False, verbose_name='الافتراضي')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
                ('priority', models.IntegerField(default=0, help_text='الأعلى يُجرَّب أولًا', verbose_name='الأولوية')),
                ('max_per_hour', models.PositiveIntegerField(default=0, verbose_name='سقف الرسائل بالساعة')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر نجاح')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر فشل')),
                ('last_error', models.TextField(blank=True, verbose_name='آخر خطأ')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, verbose_name='إخفاقات متتالية')),
            ],
            options={
                'verbose_name': 'حساب بريد',
                'verbose_name_plural': 'حسابات البريد',
                'ordering': ['-priority', 'code'],
                'indexes': [models.Index(fields=['is_active', '-priority'], name='mailing_ema_is_acti_dc8650_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('is_default',), name='unique_default_email_account')],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmailCredential',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('key', models.CharField(choices=[('password', 'كلمة مرور SMTP'), ('imap_password', 'كلمة مرور IMAP'), ('api_key', 'مفتاح API')], max_length=50, verbose_name='المفتاح')),
                ('value', core.encryption.EncryptedTextField(help_text='مشفّرة — لا تُقرأ عبر الـ API', verbose_name='القيمة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='mailing.emailaccount', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'سرّ حساب بريد',
                'verbose_name_plural': 'أسرار حسابات البريد',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('account', 'key'), name='unique_email_credential')],
            },
        ),
    ]
