# Generated by Django 5.2 on 2026-08-18 00:12

import core.models.base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailRoute',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('purpose', models.CharField(choices=[('ACCOUNT', 'الحساب والأمان'), ('ORDERS', 'الطلبات'), ('PAYMENTS', 'الدفع'), ('SHIPPING', 'الشحن'), ('INVENTORY', 'المخزون'), ('MARKETING', 'التسويق'), ('SUPPORT', 'خدمة العملاء — الوارد'), ('REPORTS', 'التقارير'), ('SYSTEM', 'النظام')], db_index=True, max_length=16, verbose_name='الغرض')),
                ('template_key', models.CharField(blank=True, help_text='اتركه فارغًا ليشمل كل قوالب الغرض', max_length=100, verbose_name='قالب بعينه')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='mailing.emailaccount', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'مسؤولية بريد',
                'verbose_name_plural': 'مسؤوليات البريد',
                'ordering': ['purpose', 'template_key'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('purpose', 'template_key'), name='unique_mail_route')],
            },
        ),
    ]
