# Generated by Django 5.2 on 2026-08-18 14:21

import core.models.base
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('to_email', models.EmailField(max_length=254, verbose_name='المستلم')),
                ('subject', models.CharField(max_length=500, verbose_name='الموضوع')),
                ('body', models.TextField(verbose_name='النص')),
                ('template_key', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='القالب')),
                ('purpose', models.CharField(blank=True, choices=[('ACCOUNT', 'الحساب والأمان'), ('ORDERS', 'الطلبات'), ('PAYMENTS', 'الدفع'), ('SHIPPING', 'الشحن'), ('INVENTORY', 'المخزون'), ('MARKETING', 'التسويق'), ('SUPPORT', 'خدمة العملاء — الوارد'), ('REPORTS', 'التقارير'), ('SYSTEM', 'النظام')], db_index=True, max_length=16, verbose_name='الغرض')),
                ('language', models.CharField(default='ar', max_length=8, verbose_name='اللغة')),
                ('status', models.CharField(choices=[('PENDING', 'في الطابور'), ('SENDING', 'قيد التسليم'), ('SENT', 'سُلّم'), ('FAILED', 'فشل نهائيًا'), ('CANCELLED', 'ألغي')], db_index=True, default='PENDING', max_length=16, verbose_name='الحالة')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='المحاولات')),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='المحاولة القادمة')),
                ('last_error', models.TextField(blank=True, verbose_name='آخر خطأ')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mailing.emailaccount', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'رسالة صادرة',
                'verbose_name_plural': 'الصادر',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='mailing_out_status_8c9fb0_idx')],
            },
        ),
    ]
