# Generated by Django 5.2 on 2026-08-18 15:04

import core.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_outboundmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateOverride',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='مفتاح القالب')),
                ('subject_ar', models.CharField(max_length=300, verbose_name='الموضوع بالعربية')),
                ('subject_en', models.CharField(max_length=300, verbose_name='الموضوع بالإنجليزية')),
                ('body_ar', models.TextField(verbose_name='النص بالعربية')),
                ('body_en', models.TextField(verbose_name='النص بالإنجليزية')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'تجاوز قالب بريد',
                'verbose_name_plural': 'تجاوزات قوالب البريد',
                'ordering': ['key'],
            },
        ),
    ]
