# Generated by Django 5.2 on 2026-08-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_templateoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateoverride',
            name='key',
            field=models.SlugField(max_length=100, verbose_name='مفتاح القالب'),
        ),
        migrations.AddConstraint(
            model_name='templateoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('key',), name='unique_active_template_override'),
        ),
    ]
