# Generated by Django 5.2 on 2026-08-19 00:43

import core.models.base
import django.db.models.deletion
import mailing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_templateoverride_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('message_id', models.CharField(db_index=True, max_length=998, verbose_name='معرّف الرسالة')),
                ('in_reply_to', models.CharField(blank=True, max_length=998, verbose_name='ردّ على')),
                ('references', models.TextField(blank=True, verbose_name='سلسلة المراجع')),
                ('from_email', models.EmailField(max_length=254, verbose_name='المرسل')),
                ('from_name', models.CharField(blank=True, max_length=255, verbose_name='اسم المرسل')),
                ('to_email', models.CharField(blank=True, max_length=998, verbose_name='إلى')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='الموضوع')),
                ('body_text', models.TextField(blank=True, verbose_name='النص')),
                ('body_html', models.TextField(blank=True, verbose_name='HTML')),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='وقت الوصول')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='الحجم')),
                ('is_auto', models.BooleanField(default=False, verbose_name='رسالة آلية')),
                ('status', models.CharField(choices=[('NEW', 'جديدة'), ('ASSIGNED', 'مُسنَدة'), ('REPLIED', 'مُجاب عليها'), ('CLOSED', 'مغلقة'), ('SPAM', 'مزعجة')], db_index=True, default='NEW', max_length=16, verbose_name='الحالة')),
                ('reference_type', models.CharField(blank=True, max_length=32, verbose_name='نوع المرجع')),
                ('reference_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف المرجع')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound', to='mailing.emailaccount', verbose_name='الصندوق')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mail', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
            ],
            options={
                'verbose_name': 'رسالة واردة',
                'verbose_name_plural': 'الوارد',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundAttachment',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('file', models.FileField(upload_to=mailing.models.inbound_attachment_path, verbose_name='الملف')),
                ('filename', models.CharField(max_length=255, verbose_name='الاسم الأصلي')),
                ('content_type', models.CharField(max_length=100, verbose_name='النوع المُتحقَّق منه')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='الحجم')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mailing.inboundmessage', verbose_name='الرسالة')),
            ],
            options={
                'verbose_name': 'مرفق وارد',
                'verbose_name_plural': 'المرفقات الواردة',
                'ordering': ['filename'],
            },
        ),
        migrations.AddIndex(
            model_name='inboundmessage',
            index=models.Index(fields=['status', '-received_at'], name='mailing_inb_status_b2a2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundmessage',
            index=models.Index(fields=['from_email', '-received_at'], name='mailing_inb_from_em_1fb9fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('account', 'message_id'), name='unique_inbound_message'),
        ),
    ]
