# Generated by Django 5.2 on 2026-08-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_inboundmessage_inboundattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmessage',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=998, verbose_name='ردّ على'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='references',
            field=models.TextField(blank=True, verbose_name='سلسلة المراجع'),
        ),
    ]
