# Generated by Django 5.2 on 2026-08-12 17:29

import administration.models
import core.models.base
import core.models.translatable
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('admin_number', models.CharField(default=administration.models.admin_number, editable=False, max_length=24, unique=True, verbose_name='الرقم الإداري')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='القسم')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='المسمى الوظيفي')),
                ('is_owner', models.BooleanField(default=False, help_text='الحساب الجذر — لا يُوقَف ولا تُسحب صلاحياته', verbose_name='المالك')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مدير نظام',
                'verbose_name_plural': 'مديرو النظام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('code', models.SlugField(unique=True, verbose_name='الرمز')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('is_system', models.BooleanField(default=False, help_text='لا يُحذف ولا يُعاد تسميته', verbose_name='دور نظام')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
                ('permissions', models.ManyToManyField(blank=True, related_name='admin_roles', to='auth.permission', verbose_name='الصلاحيات')),
            ],
            options={
                'verbose_name': 'دور إداري',
                'verbose_name_plural': 'الأدوار الإدارية',
                'ordering': ['code'],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AdminRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('from_date', models.DateField(auto_now_add=True, verbose_name='من تاريخ')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='حتى تاريخ')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='administration.adminprofile', verbose_name='المدير')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أسنده')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='administration.adminrole', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'إسناد دور',
                'verbose_name_plural': 'إسنادات الأدوار',
                'ordering': ['-from_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='adminprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_owner', True)), fields=('is_owner',), name='unique_system_owner'),
        ),
        migrations.AddIndex(
            model_name='adminroleassignment',
            index=models.Index(fields=['admin', 'role'], name='administrat_admin_i_c0f818_idx'),
        ),
    ]
