# Generated by Django 5.2 on 2026-08-15 11:06

import b2b.models
import core.models.base
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0002_alter_order_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('kind', models.CharField(choices=[('PHARMACY', 'صيدلية'), ('WAREHOUSE', 'مخزن أدوية'), ('CLINIC', 'عيادة'), ('HOSPITAL', 'مستشفى'), ('TRADER', 'تاجر')], db_index=True, max_length=16, verbose_name='نوع المنشأة')),
                ('legal_name', models.CharField(max_length=250, verbose_name='الاسم القانوني')),
                ('license_number', models.CharField(blank=True, max_length=64, verbose_name='رقم الترخيص')),
                ('license_expires_on', models.DateField(blank=True, null=True, verbose_name='انتهاء الترخيص')),
                ('credit_status', models.CharField(choices=[('NONE', 'بلا ائتمان — دفع مقدَّم'), ('ACTIVE', 'ائتمان نشط'), ('SUSPENDED', 'موقوف')], db_index=True, default='NONE', max_length=16, verbose_name='حالة الائتمان')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الحد الائتماني')),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=0, verbose_name='مهلة السداد (يوم)')),
                ('credit_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المنح')),
                ('credit_note', models.TextField(blank=True, verbose_name='ملاحظة الائتمان')),
                ('credit_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_credit_accounts', to=settings.AUTH_USER_MODEL, verbose_name='مانح الائتمان')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='customers.customerprofile', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'ملف تجاري',
                'verbose_name_plural': 'الملفات التجارية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('number', models.CharField(default=b2b.models.invoice_number, editable=False, max_length=24, unique=True, verbose_name='رقم الفاتورة')),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الإصدار')),
                ('due_on', models.DateField(db_index=True, verbose_name='تاريخ الاستحقاق')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي قبل الخصم')),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الخصم')),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الضريبة')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي')),
                ('status', models.CharField(choices=[('ISSUED', 'صادرة'), ('PAID', 'مسدَّدة'), ('OVERDUE', 'متأخرة'), ('CANCELLED', 'ملغاة')], db_index=True, default='ISSUED', max_length=16, verbose_name='الحالة')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='b2b.businessprofile', verbose_name='العميل')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-issued_on', '-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='b2b_invoice_busines_63bef1_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('kind', models.CharField(choices=[('CHARGE', 'مديونية — طلب آجل'), ('PAYMENT', 'سداد'), ('CREDIT_NOTE', 'إشعار دائن — مرتجع'), ('ADJUSTMENT', 'تسوية يدوية')], db_index=True, max_length=16, verbose_name='النوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ')),
                ('occurred_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('due_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='المرجع')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='b2b.businessprofile', verbose_name='العميل')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='orders.order', verbose_name='الطلب')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='سجّلها')),
            ],
            options={
                'verbose_name': 'حركة حساب',
                'verbose_name_plural': 'حركات الحساب',
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['business', '-occurred_on'], name='b2b_ledgere_busines_8c9255_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('order__isnull', False)), fields=('order', 'kind'), name='unique_ledger_entry_per_order_kind')],
            },
        ),
    ]
