# Generated by Django 5.2 on 2026-08-15 12:11

import core.models.base
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='الرمز')),
                ('kind', models.CharField(choices=[('SALES_REP', 'مندوب مبيعات'), ('SENIOR_SALES', 'مندوب أول'), ('SALES_MANAGER', 'مدير مبيعات'), ('CUSTOMER_SERVICE', 'خدمة عملاء'), ('WAREHOUSE', 'موظف مخزن'), ('FINANCE', 'موظف مالي'), ('OPERATIONS', 'عمليات')], db_index=True, max_length=24, verbose_name='النوع')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=120, verbose_name='الاسم بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('permissions', models.ManyToManyField(blank=True, related_name='employee_roles', to='auth.permission', verbose_name='الصلاحيات')),
            ],
            options={
                'verbose_name': 'دور وظيفي',
                'verbose_name_plural': 'الأدوار الوظيفية',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('employee_number', models.CharField(max_length=32, unique=True, verbose_name='الرقم الوظيفي')),
                ('phone_extension', models.CharField(blank=True, max_length=16, verbose_name='التحويلة')),
                ('hired_on', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='على رأس العمل')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team', to='employees.employeeprofile', verbose_name='المدير المباشر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.employeerole', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'ملف موظف',
                'verbose_name_plural': 'ملفات الموظفين',
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAssignment',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('status', models.CharField(choices=[('ACTIVE', 'قائم'), ('ENDED', 'منتهٍ')], db_index=True, default='ACTIVE', max_length=16, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='بداية الإسناد')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='نهاية الإسناد')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL, verbose_name='أسنده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='customers.customerprofile', verbose_name='العميل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employees.employeeprofile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'إسناد عميل',
                'verbose_name_plural': 'إسنادات العملاء',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='employees_c_employe_ce7ca4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'ACTIVE')), fields=('customer',), name='one_active_assignment_per_customer')],
            },
        ),
    ]
