# Generated by Django 5.2 on 2026-08-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_role', to='auth.group', verbose_name='مجموعة الصلاحيات'),
        ),
    ]
