# Generated by Django 4.2.16 on 2026-08-12 16:17

import core.models.base
import core.models.tax
import core.models.translatable
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'إنشاء'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('RESTORE', 'استرجاع'), ('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج'), ('LOGIN_FAILED', 'محاولة دخول فاشلة'), ('SUSPEND', 'إيقاف حساب'), ('ACTIVATE', 'تفعيل حساب'), ('APPROVE', 'اعتماد'), ('REJECT', 'رفض'), ('PRICE_CHANGE', 'تغيير سعر'), ('STOCK_CHANGE', 'تغيير مخزون'), ('PERMISSION_CHANGE', 'تغيير صلاحيات'), ('SETTING_CHANGE', 'تغيير إعداد'), ('REFUND', 'استرداد'), ('EXPORT', 'تصدير بيانات')], max_length=32, verbose_name='الإجراء')),
                ('object_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='معرّف الكائن')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='وصف الكائن')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{"field": {"old": ..., "new": ...}}', verbose_name='التغييرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='الوقت')),
            ],
            options={
                'verbose_name': 'قيد تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('key', models.SlugField(max_length=100, primary_key=True, serialize=False, verbose_name='المفتاح')),
                ('value', models.JSONField(verbose_name='القيمة')),
                ('value_type', models.CharField(choices=[('STRING', 'نص'), ('INT', 'رقم صحيح'), ('DECIMAL', 'رقم عشري'), ('BOOL', 'صح/خطأ'), ('JSON', 'JSON')], max_length=16, verbose_name='نوع القيمة')),
                ('group', models.CharField(choices=[('general', 'عام'), ('tax', 'الضريبة'), ('inventory', 'المخزون'), ('orders', 'الطلبات'), ('pricing', 'التسعير'), ('loyalty', 'الولاء'), ('security', 'الأمان'), ('notifications', 'الإشعارات')], db_index=True, default='general', max_length=32, verbose_name='المجموعة')),
                ('label_ar', models.CharField(max_length=200, verbose_name='الوصف بالعربية')),
                ('label_en', models.CharField(max_length=200, verbose_name='الوصف بالإنجليزية')),
                ('help_text_ar', models.TextField(blank=True, verbose_name='شرح بالعربية')),
                ('help_text_en', models.TextField(blank=True, verbose_name='شرح بالإنجليزية')),
                ('is_editable', models.BooleanField(default=True, verbose_name='قابل للتحرير')),
            ],
            options={
                'verbose_name': 'إعداد نظام',
                'verbose_name_plural': 'إعدادات النظام',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('code', models.SlugField(unique=True, verbose_name='الرمز')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='النسبة %')),
                ('is_default', models.BooleanField(default=False, verbose_name='الافتراضية')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
                ('valid_from', models.DateField(default=core.models.tax.today, verbose_name='سارية من')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='سارية حتى')),
            ],
            options={
                'verbose_name': 'فئة ضريبية',
                'verbose_name_plural': 'الفئات الضريبية',
                'ordering': ['code'],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='taxclass',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('is_default',), name='unique_default_tax_class'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='core_auditl_content_fec0c4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', '-created_at'], name='core_auditl_actor_i_502baf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx'),
        ),
    ]
