# Generated by Django 5.2 on 2026-08-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_start', models.DateTimeField(db_index=True, verbose_name='بداية الساعة')),
                ('device_type', models.CharField(choices=[('DESKTOP', 'حاسوب'), ('TABLET', 'لوحي'), ('MOBILE', 'هاتف'), ('UNKNOWN', 'غير معروف')], default='UNKNOWN', max_length=16, verbose_name='نوع الجهاز')),
                ('requests', models.PositiveIntegerField(default=0, verbose_name='عدد الطلبات')),
                ('guest_visitors', models.PositiveIntegerField(default=0, verbose_name='زوار مجهولون')),
                ('known_visitors', models.PositiveIntegerField(default=0, verbose_name='زوار مسجَّلون')),
            ],
            options={
                'verbose_name': 'ساعة حركة',
                'verbose_name_plural': 'حركة الاستخدام',
                'ordering': ['-bucket_start'],
                'indexes': [models.Index(fields=['-bucket_start', 'device_type'], name='analytics_t_bucket__aabcc7_idx')],
                'constraints': [models.UniqueConstraint(fields=('bucket_start', 'device_type'), name='unique_traffic_bucket')],
            },
        ),
    ]
