# Generated by Django 5.2 on 2026-08-15 10:12

import core.models.base
import django.core.validators
import django.db.models.deletion
import finance.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=120, verbose_name='الاسم بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.expensecategory', verbose_name='البند الأب')),
            ],
            options={
                'verbose_name': 'بند مصروف',
                'verbose_name_plural': 'بنود المصروفات',
                'ordering': ['display_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='RevenueEntry',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('source', models.CharField(choices=[('ORDER', 'طلب'), ('REFUND', 'مرتجع')], db_index=True, max_length=16, verbose_name='المصدر')),
                ('gross', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي قبل الخصم')),
                ('discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الخصومات')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الضريبة')),
                ('net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='صافي المبيعات')),
                ('channel', models.CharField(blank=True, db_index=True, max_length=16, verbose_name='القناة')),
                ('occurred_on', models.DateField(db_index=True, verbose_name='تاريخ الاستحقاق')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_entries', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'قيد إيراد',
                'verbose_name_plural': 'قيود الإيراد',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='COGSEntry',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='التكلفة')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('unknown_quantity', models.PositiveIntegerField(default=0, help_text='بضاعة بلا دفعة مرتبطة — تكلفتها غير معروفة', verbose_name='كمية بتكلفة مجهولة')),
                ('revenue_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cogs', to='finance.revenueentry', verbose_name='قيد الإيراد')),
            ],
            options={
                'verbose_name': 'قيد تكلفة',
                'verbose_name_plural': 'قيود التكلفة',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ')),
                ('incurred_on', models.DateField(db_index=True, verbose_name='تاريخ الاستحقاق')),
                ('vendor_name', models.CharField(blank=True, max_length=200, verbose_name='المورّد/الجهة')),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='رقم الفاتورة')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=finance.models.expense_attachment_path, verbose_name='مرفق الفاتورة')),
                ('payment_mean', models.CharField(choices=[('CASH', 'نقدًا'), ('BANK', 'تحويل بنكي'), ('CARD', 'بطاقة'), ('OTHER', 'أخرى')], default='CASH', max_length=16, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('DRAFT', 'مسوّدة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض')], db_index=True, default='DRAFT', max_length=16, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='المُعتمِد')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_expenses', to=settings.AUTH_USER_MODEL, verbose_name='المُدخِل')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory', verbose_name='البند')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-incurred_on', '-created_at'],
                'indexes': [models.Index(fields=['status', 'incurred_on'], name='finance_exp_status_2c111d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('is_closed', models.BooleanField(db_index=True, default=False, verbose_name='مقفلة')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإقفال')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL, verbose_name='أقفلها')),
            ],
            options={
                'verbose_name': 'فترة مالية',
                'verbose_name_plural': 'الفترات المالية',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_fiscal_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='revenueentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('source', 'order'), name='unique_revenue_entry_per_source_order'),
        ),
    ]
