# Generated by Django 5.2 on 2026-08-13 04:05

import core.models.base
import core.models.translatable
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pricing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('code', models.SlugField(unique=True, verbose_name='الرمز')),
                ('kind', models.CharField(choices=[('RETAIL', 'تجزئة'), ('WHOLESALE', 'جملة'), ('STUDENT', 'طلاب'), ('PROFESSIONAL', 'مهنيون'), ('CONTRACT', 'عقد خاص')], db_index=True, default='RETAIL', max_length=16, verbose_name='النوع')),
                ('account_types', models.JSONField(blank=True, default=list, verbose_name='أنواع الحسابات')),
                ('priority', models.IntegerField(default=0, help_text='الأعلى يفوز عند تطابق أكثر من قائمة', verbose_name='الأولوية')),
                ('is_default', models.BooleanField(default=False, verbose_name='الافتراضية')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
                ('valid_from', models.DateField(default=pricing.models.today, verbose_name='سارية من')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='سارية حتى')),
            ],
            options={
                'verbose_name': 'قائمة أسعار',
                'verbose_name_plural': 'قوائم الأسعار',
                'ordering': ['-priority', 'code'],
                'indexes': [models.Index(fields=['is_active', '-priority'], name='pricing_pri_is_acti_2ae142_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('is_default',), name='unique_default_price_list')],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PriceOverride',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('discount_kind', models.CharField(choices=[('PERCENTAGE', 'نسبة مئوية'), ('FIXED', 'مبلغ ثابت')], max_length=16, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قيمة الخصم')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='يبدأ في')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
                ('price_list', models.ForeignKey(blank=True, help_text='فارغ = كل القوائم', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='pricing.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='catalog.product', verbose_name='المنتج')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'خصم ترويجي',
                'verbose_name_plural': 'الخصومات الترويجية',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['product', 'is_active', 'starts_at', 'ends_at'], name='pricing_pri_product_e3e7e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='يُطبَّق هذا السعر من هذه الكمية فأكثر', verbose_name='الكمية الدنيا')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pricing.pricelist', verbose_name='القائمة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='catalog.product', verbose_name='المنتج')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='catalog.productvariant', verbose_name='النسخة')),
            ],
            options={
                'verbose_name': 'قاعدة تسعير',
                'verbose_name_plural': 'قواعد التسعير',
                'ordering': ['-min_quantity'],
                'indexes': [models.Index(fields=['price_list', 'product', '-min_quantity'], name='pricing_pri_price_l_1dc255_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('price_list', 'product', 'variant', 'min_quantity'), name='unique_price_rule')],
            },
        ),
    ]
