# Generated by Django 5.2 on 2026-08-16 23:07

import core.models.base
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0002_alter_order_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=120, verbose_name='الاسم بالإنجليزية')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='إيقافه يمنع الكسب الجديد ولا يمحو الأرصدة', verbose_name='مفعّل')),
                ('redemption_enabled', models.BooleanField(default=True, verbose_name='الاستبدال مفعّل')),
                ('account_types', models.JSONField(blank=True, default=list, help_text='فارغ = الجميع · مثال: طلاب وصيادلة فقط', verbose_name='أنواع الحسابات')),
                ('customer_segments', models.JSONField(blank=True, default=list, help_text='فارغ = الجميع · يُطبَّق مع أنواع الحسابات معًا', verbose_name='تصنيفات العملاء')),
                ('currency_per_point', models.DecimalField(decimal_places=2, default=10, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='قيمة الجنيه لكل نقطة')),
                ('point_value', models.DecimalField(decimal_places=4, default=0.01, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قيمة النقطة')),
                ('earns_on_tax', models.BooleanField(default=False, verbose_name='الكسب على الضريبة')),
                ('earns_on_shipping', models.BooleanField(default=False, verbose_name='الكسب على الشحن')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الحد الأدنى للطلب')),
                ('expiry_months', models.PositiveSmallIntegerField(default=12, help_text='صفر = بلا انتهاء — يُختار صراحةً', verbose_name='مدة الصلاحية (شهر)')),
                ('reverse_on_refund', models.BooleanField(default=True, verbose_name='سحب النقاط عند المرتجع')),
                ('max_redemption_percent', models.DecimalField(decimal_places=2, default=50, help_text='لئلا يُدفَع طلب كامل بالنقاط', max_digits=5, verbose_name='أقصى نسبة استبدال ٪')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
            ],
            options={
                'verbose_name': 'برنامج ولاء',
                'verbose_name_plural': 'برامج الولاء',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=120, verbose_name='الاسم بالإنجليزية')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='مفعّل')),
                ('account_types', models.JSONField(blank=True, default=list, help_text='فارغ = الجميع', verbose_name='أنواع الحسابات')),
                ('referrer_points', models.PositiveIntegerField(default=100, verbose_name='نقاط المُحيل')),
                ('referee_points', models.PositiveIntegerField(default=50, verbose_name='نقاط المُحال')),
                ('max_referrals_per_user', models.PositiveIntegerField(default=0, help_text='صفر = بلا سقف', verbose_name='أقصى إحالات لكل مستخدم')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الحد الأدنى لطلب المُحال')),
            ],
            options={
                'verbose_name': 'برنامج إحالة',
                'verbose_name_plural': 'برامج الإحالة',
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='الكود')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'كود إحالة',
                'verbose_name_plural': 'أكواد الإحالة',
            },
        ),
        migrations.CreateModel(
            name='PointsEntry',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('kind', models.CharField(choices=[('EARN', 'كسب'), ('REDEEM', 'استبدال'), ('EXPIRE', 'انتهاء صلاحية'), ('REVERSE', 'سحب — مرتجع'), ('REFERRAL', 'مكافأة إحالة'), ('ADJUSTMENT', 'تسوية يدوية — إضافة'), ('DEDUCTION', 'تسوية يدوية — سحب')], db_index=True, max_length=16, verbose_name='النوع')),
                ('points', models.PositiveIntegerField(verbose_name='النقاط')),
                ('expires_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='تنتهي في')),
                ('points_remaining', models.PositiveIntegerField(default=0, verbose_name='المتبقي من الدفعة')),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='المرجع')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_entries', to='customers.customerprofile', verbose_name='العميل')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_entries', to='orders.order', verbose_name='الطلب')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='loyalty.loyaltyprogram', verbose_name='البرنامج')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_points', to=settings.AUTH_USER_MODEL, verbose_name='سجّلها')),
            ],
            options={
                'verbose_name': 'حركة نقاط',
                'verbose_name_plural': 'حركات النقاط',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='loyalty_poi_custome_0b11c8_idx'), models.Index(fields=['kind', 'expires_on'], name='loyalty_poi_kind_8aaa8d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('order__isnull', False)), fields=('order', 'kind'), name='unique_points_entry_per_order_kind')],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار أول طلب'), ('REWARDED', 'مُكافأة'), ('REJECTED', 'مرفوضة — اشتباه تلاعب')], db_index=True, default='PENDING', max_length=16, verbose_name='الحالة')),
                ('rewarded_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المكافأة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('signup_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان التسجيل')),
                ('qualifying_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualified_referrals', to='orders.order', verbose_name='الطلب المؤهِّل')),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referred_by', to=settings.AUTH_USER_MODEL, verbose_name='المُحال')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='المُحيل')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='loyalty.referralprogram', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'إحالة',
                'verbose_name_plural': 'الإحالات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referrer', 'status'], name='loyalty_ref_referre_8707e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TierLevel',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.SlugField(max_length=64, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=120, verbose_name='الاسم بالإنجليزية')),
                ('threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='عتبة الإنفاق')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مضاعِف الكسب')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='loyalty.loyaltyprogram', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'فئة ولاء',
                'verbose_name_plural': 'فئات الولاء',
                'ordering': ['program', 'threshold'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('program', 'code'), name='unique_tier_code_per_program')],
            },
        ),
    ]
