# Generated by Django 5.2 on 2026-08-13 22:56

import branding.models
import core.models.base
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.SlugField(unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='اسم الموقع بالعربية')),
                ('name_en', models.CharField(max_length=120, verbose_name='اسم الموقع بالإنجليزية')),
                ('tagline_ar', models.CharField(blank=True, max_length=200, verbose_name='الشعار النصي عربي')),
                ('tagline_en', models.CharField(blank=True, max_length=200, verbose_name='الشعار النصي إنجليزي')),
                ('logo_light', models.ImageField(blank=True, upload_to=branding.models.branding_asset_path, verbose_name='اللوجو — الوضع الفاتح')),
                ('logo_dark', models.ImageField(blank=True, upload_to=branding.models.branding_asset_path, verbose_name='اللوجو — الوضع الداكن')),
                ('icon', models.ImageField(blank=True, help_text='للتطبيق والمشاركة — مربّعة', upload_to=branding.models.branding_asset_path, verbose_name='الأيقونة المربّعة')),
                ('favicon', models.ImageField(blank=True, upload_to=branding.models.branding_asset_path, verbose_name='أيقونة المتصفح')),
                ('og_image', models.ImageField(blank=True, help_text='تظهر عند مشاركة رابط الموقع — 1200×630', upload_to=branding.models.branding_asset_path, verbose_name='صورة المشاركة')),
                ('font_ar', models.CharField(default='Cairo', max_length=120, verbose_name='الخط العربي')),
                ('font_en', models.CharField(default='Inter', max_length=120, verbose_name='الخط الإنجليزي')),
                ('font_size_base', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.75')), django.core.validators.MaxValueValidator(Decimal('1.5'))], verbose_name='حجم الخط الأساسي (rem)')),
                ('radius', models.DecimalField(decimal_places=3, default=Decimal('0.500'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('2'))], verbose_name='استدارة الحواف (rem)')),
                ('shadow_level', models.PositiveSmallIntegerField(default=1, help_text='0 = بلا ظل · 3 = ظل عميق', validators=[django.core.validators.MaxValueValidator(3)], verbose_name='مستوى الظل')),
                ('default_mode', models.CharField(choices=[('LIGHT', 'فاتح دائمًا'), ('DARK', 'داكن دائمًا'), ('SYSTEM', 'حسب تفضيل الجهاز')], default='SYSTEM', max_length=8, verbose_name='الوضع الافتراضي')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد التواصل')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف التواصل')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='واتساب')),
                ('address_ar', models.CharField(blank=True, max_length=300, verbose_name='العنوان بالعربية')),
                ('address_en', models.CharField(blank=True, max_length=300, verbose_name='العنوان بالإنجليزية')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('instagram', models.URLField(blank=True, verbose_name='إنستجرام')),
                ('x_twitter', models.URLField(blank=True, verbose_name='إكس')),
                ('linkedin', models.URLField(blank=True, verbose_name='لينكدإن')),
                ('youtube', models.URLField(blank=True, verbose_name='يوتيوب')),
                ('tiktok', models.URLField(blank=True, verbose_name='تيك توك')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'ملف هوية',
                'verbose_name_plural': 'ملفات الهوية',
                'ordering': ['-is_active', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('is_active',), name='unique_active_brand_profile')],
            },
        ),
        migrations.CreateModel(
            name='ThemePalette',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('mode', models.CharField(choices=[('LIGHT', 'فاتح'), ('DARK', 'داكن')], max_length=8, verbose_name='الوضع')),
                ('primary', models.CharField(default='#2e7d32', max_length=7, validators=[django.core.validators.RegexValidator(message='لون غير صالح — استخدم صيغة #rrggbb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='الأساسي')),
                ('on_primary', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='لون غير صالح — استخدم صيغة #rrggbb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='النص فوق الأساسي')),
                ('secondary', models.CharField(default='#00695c', max_length=7, validators=[django.core.validators.RegexValidator(message='لون غير صالح — استخدم صيغة #rrggbb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='الثانوي')),
                ('accent', models.CharField(default='#f9a825', max_length=7, validators=[django.core.validators.RegexValidator(message='لون غير صالح — استخدم صيغة #rrggbb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='المميّز')),
                ('success', models.CharField(default='#2e7d32', max_length=7, validators=[django.core.validators.RegexValidator(message='لون غير صالح — استخدم صيغة #rrggbb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='نجاح')),
                ('warning', models.CharField(default='#ef6c00', max_length=7, validators=[django.core.validators.RegexValidator(message='لون غير صالح — استخدم صيغة #rrggbb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='تحذير')),
                ('danger', models.CharField(default='#c62828', max_length=7, validators=[django.core.validators.RegexValidator(message='لون غير صالح — استخدم صيغة #rrggbb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='خطر')),
                ('info', models.CharField(default='#0277bd', max_length=7, validators=[django.core.validators.RegexValidator(message='لون غير صالح — استخدم صيغة #rrggbb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='معلومة')),
                ('bg', models.CharField(default='#f7f8fa', max_length=7, validators=[django.core.validators.RegexValidator(message='لون غير صالح — استخدم صيغة #rrggbb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='الخلفية')),
                ('surface', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='لون غير صالح — استخدم صيغة #rrggbb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='السطح')),
                ('border', models.CharField(default='#e3e6ea', max_length=7, validators=[django.core.validators.RegexValidator(message='لون غير صالح — استخدم صيغة #rrggbb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='الحدود')),
                ('text', models.CharField(default='#1b1f23', max_length=7, validators=[django.core.validators.RegexValidator(message='لون غير صالح — استخدم صيغة #rrggbb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='النص')),
                ('text_muted', models.CharField(default='#5c6670', max_length=7, validators=[django.core.validators.RegexValidator(message='لون غير صالح — استخدم صيغة #rrggbb', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='النص الخافت')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to='branding.brandprofile', verbose_name='ملف الهوية')),
            ],
            options={
                'verbose_name': 'لوحة ألوان',
                'verbose_name_plural': 'لوحات الألوان',
                'ordering': ['profile', 'mode'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'mode'), name='unique_palette_per_mode')],
            },
        ),
    ]
