# Generated by Django 5.2 on 2026-08-25 02:08

import core.models.base
import django.db.models.deletion
import imports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('file', models.FileField(upload_to=imports.models.import_file_path, verbose_name='الملف')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='بصمة الملف')),
                ('mode', models.CharField(db_index=True, max_length=16, verbose_name='النمط')),
                ('status', models.CharField(choices=[('UPLOADED', 'مرفوع'), ('VALIDATING', 'قيد الفحص'), ('VALIDATED', 'جاهز للتنفيذ'), ('REJECTED', 'مرفوض — أخطاء تمنع التنفيذ'), ('RUNNING', 'قيد التنفيذ'), ('DONE', 'اكتمل'), ('PARTIAL', 'اكتمل بأخطاء جزئية'), ('FAILED', 'فشل'), ('CANCELLED', 'ملغى')], db_index=True, default='UPLOADED', max_length=16, verbose_name='الحالة')),
                ('phase', models.CharField(choices=[('PRODUCTS', 'المنتجات'), ('VARIANTS', 'النسخ'), ('STOCK', 'الرصيد الافتتاحي'), ('FINISHED', 'انتهى')], default='PRODUCTS', max_length=16, verbose_name='المرحلة')),
                ('row_counts', models.JSONField(blank=True, default=dict, verbose_name='عدد الصفوف')),
                ('cursor', models.PositiveIntegerField(default=0, verbose_name='المؤشر')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='المُنشأ')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='المُحدَّث')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='المتخطّى')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='الفاشل')),
                ('preview', models.JSONField(blank=True, default=dict, verbose_name='نتيجة الفحص')),
                ('create_missing_brands', models.BooleanField(default=False, verbose_name='إنشاء البراندات الناقصة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بدأ في')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى في')),
                ('heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='آخر نبضة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='بدأها')),
            ],
            options={
                'verbose_name': 'وظيفة استيراد',
                'verbose_name_plural': 'وظائف الاستيراد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRowError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('sheet', models.CharField(db_index=True, max_length=20, verbose_name='الورقة')),
                ('row_number', models.PositiveIntegerField(verbose_name='رقم الصف')),
                ('column', models.CharField(blank=True, max_length=64, verbose_name='العمود')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='القيمة')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('identifier', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='المعرّف')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='imports.importjob', verbose_name='الوظيفة')),
            ],
            options={
                'verbose_name': 'خطأ صف',
                'verbose_name_plural': 'أخطاء الصفوف',
                'ordering': ['sheet', 'row_number', 'column'],
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', '-created_at'], name='imports_imp_status_d38bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', 'heartbeat_at'], name='imports_imp_status_397911_idx'),
        ),
        migrations.AddIndex(
            model_name='importrowerror',
            index=models.Index(fields=['job', 'sheet', 'row_number'], name='imports_imp_job_id_a5b6e5_idx'),
        ),
    ]
