# Generated by Django 4.2.16 on 2026-08-12 16:17

import accounts.models
import core.models.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'هذا البريد مسجل بالفعل'}, max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, help_text='بصيغة E.164 — مثال: +201001234567', max_length=20, null=True, unique=True, verbose_name='رقم الهاتف')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='الاسم الأخير')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='الصورة')),
                ('account_type', models.CharField(choices=[('GUEST', 'زائر'), ('STUDENT', 'طالب'), ('DOCTOR', 'طبيب'), ('PHARMACIST', 'صيدلي'), ('PHARMACY', 'صيدلية'), ('WAREHOUSE', 'مخزن'), ('TRADER', 'تاجر'), ('SUPPLIER', 'مورّد'), ('EMPLOYEE', 'موظف'), ('ADMIN', 'مدير نظام')], db_index=True, default='STUDENT', max_length=16, verbose_name='نوع الحساب')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('SUSPENDED', 'موقوف'), ('BLOCKED', 'محظور')], db_index=True, default='ACTIVE', max_length=16, verbose_name='حالة الحساب')),
                ('verification_status', models.CharField(choices=[('NOT_REQUIRED', 'غير مطلوب'), ('PENDING', 'قيد المراجعة'), ('VERIFIED', 'موثّق'), ('REJECTED', 'مرفوض')], db_index=True, default='NOT_REQUIRED', max_length=16, verbose_name='حالة التوثيق')),
                ('preferred_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'الإنجليزية')], default='ar', help_text='تحدد لغة كل بريد يصل هذا المستخدم', max_length=2, verbose_name='اللغة المفضلة')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تأكيد البريد')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تأكيد الهاتف')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعّل')),
                ('is_staff', models.BooleanField(default=False, help_text='لوحة Django فقط — ليست نموذج الصلاحيات', verbose_name='وصول لوحة Django')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر دخول')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('ACTIVE', 'نشط'), ('SUSPENDED', 'موقوف'), ('BLOCKED', 'محظور')], max_length=16, verbose_name='من حالة')),
                ('to_status', models.CharField(choices=[('ACTIVE', 'نشط'), ('SUSPENDED', 'موقوف'), ('BLOCKED', 'محظور')], max_length=16, verbose_name='إلى حالة')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='الوقت')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='نفّذه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تغيير حالة حساب',
                'verbose_name_plural': 'تغييرات حالات الحسابات',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True, verbose_name='مفتاح الجلسة')),
                ('login_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الدخول')),
                ('logout_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('last_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='آخر نشاط')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإبطال')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='المتصفح')),
                ('device_type', models.CharField(choices=[('DESKTOP', 'حاسوب'), ('TABLET', 'لوحي'), ('MOBILE', 'هاتف'), ('UNKNOWN', 'غير معروف')], default='UNKNOWN', max_length=16, verbose_name='نوع الجهاز')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='المدة بالثواني')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة',
                'verbose_name_plural': 'الجلسات',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', '-last_activity'], name='accounts_us_user_id_018f2c_idx'), models.Index(fields=['-last_activity'], name='accounts_us_last_ac_8d8f08_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('purpose', models.CharField(choices=[('EMAIL_VERIFICATION', 'تأكيد البريد'), ('PASSWORD_RESET', 'استرجاع كلمة المرور'), ('EMAIL_CHANGE', 'تغيير البريد')], max_length=32, verbose_name='الغرض')),
                ('token_hash', models.CharField(db_index=True, max_length=128, verbose_name='بصمة الرمز')),
                ('expires_at', models.DateTimeField(verbose_name='تنتهي في')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='استُخدم في')),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP الطالب')),
                ('new_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الجديد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_tokens', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز أمني',
                'verbose_name_plural': 'الرموز الأمنية',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', '-created_at'], name='accounts_se_user_id_8c02d8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_type', 'status'], name='accounts_us_account_ad22ca_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'verification_status'], name='accounts_us_status_b2c756_idx'),
        ),
    ]
