# Generated by Django 5.2 on 2026-08-13 13:07

import academic.models
import core.models.base
import core.models.translatable
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='المعرّف النصي')),
                ('code', models.SlugField(verbose_name='الرمز')),
                ('years_count', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='عدد سنوات الدراسة')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'الكليات',
                'ordering': ['university', 'name_ar'],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='المعرّف النصي')),
                ('code', models.SlugField(unique=True, verbose_name='الرمز')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('governorate', models.CharField(blank=True, max_length=100, verbose_name='المحافظة')),
                ('logo', models.ImageField(blank=True, upload_to=academic.models.academic_image_path, verbose_name='الشعار')),
                ('website', models.URLField(blank=True, verbose_name='الموقع')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'جامعة',
                'verbose_name_plural': 'الجامعات',
                'ordering': ['name_ar'],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='المعرّف النصي')),
                ('code', models.SlugField(verbose_name='الرمز')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='academic.faculty', verbose_name='الكلية')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['faculty', 'name_ar'],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StudyBundle',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='المعرّف النصي')),
                ('academic_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='السنة الدراسية')),
                ('kind', models.CharField(choices=[('REQUIRED', 'مستلزمات مطلوبة'), ('RECOMMENDED', 'مستلزمات موصى بها'), ('OPTIONAL', 'اختيارية')], db_index=True, default='RECOMMENDED', max_length=16, verbose_name='النوع')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('image', models.ImageField(blank=True, upload_to=academic.models.academic_image_path, verbose_name='الصورة')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
                ('department', models.ForeignKey(blank=True, help_text='فارغ = كل أقسام الكلية', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='academic.department', verbose_name='القسم')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='academic.faculty', verbose_name='الكلية')),
            ],
            options={
                'verbose_name': 'حزمة دراسية',
                'verbose_name_plural': 'الحزم الدراسية',
                'ordering': ['academic_year', 'display_order'],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('is_essential', models.BooleanField(default=True, help_text='غير الأساسي قابل للاستبعاد عند إضافة الحزمة', verbose_name='أساسي')),
                ('note_ar', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة بالعربية')),
                ('note_en', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة بالإنجليزية')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_items', to='catalog.product', verbose_name='المنتج')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bundle_items', to='catalog.productvariant')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academic.studybundle')),
            ],
            options={
                'verbose_name': 'صنف حزمة',
                'verbose_name_plural': 'أصناف الحزم',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('academic_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='السنة الدراسية')),
                ('student_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الجامعي')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='بعد اعتماد الكارنيه الجامعي', verbose_name='موثّق')),
                ('expected_graduation_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سنة التخرّج المتوقعة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.department', verbose_name='القسم')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.faculty', verbose_name='الكلية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.university', verbose_name='الجامعة')),
            ],
            options={
                'verbose_name': 'ملف طالب',
                'verbose_name_plural': 'ملفات الطلاب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculties', to='academic.university', verbose_name='الجامعة'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('faculty', 'code'), name='unique_department_code_per_faculty'),
        ),
        migrations.AddIndex(
            model_name='studybundle',
            index=models.Index(fields=['faculty', 'academic_year', 'is_active'], name='academic_st_faculty_12b2d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='bundleitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('bundle', 'product', 'variant'), name='unique_bundle_item'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['university', 'faculty', 'academic_year'], name='academic_st_univers_2597c7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['faculty', 'academic_year', 'is_verified'], name='academic_st_faculty_715c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['university', 'is_active'], name='academic_fa_univers_7dca65_idx'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('university', 'code'), name='unique_faculty_code_per_university'),
        ),
    ]
