# Generated by Django 5.2 on 2026-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='يُولَّد تلقائيًا ولا يتغيّر بعدها — تغييره يكسر الروابط', max_length=255, unique=True, verbose_name='المعرّف النصي'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='يُولَّد تلقائيًا ولا يتغيّر بعدها — تغييره يكسر الروابط', max_length=255, unique=True, verbose_name='المعرّف النصي'),
        ),
        migrations.AlterField(
            model_name='studybundle',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='يُولَّد تلقائيًا ولا يتغيّر بعدها — تغييره يكسر الروابط', max_length=255, unique=True, verbose_name='المعرّف النصي'),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='يُولَّد تلقائيًا ولا يتغيّر بعدها — تغييره يكسر الروابط', max_length=255, unique=True, verbose_name='المعرّف النصي'),
        ),
    ]
