# Generated by Django 5.2 on 2026-08-12 23:22

import core.models.base
import core.models.translatable
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('code', models.SlugField(unique=True, verbose_name='الرمز')),
                ('kind', models.CharField(choices=[('WAREHOUSE', 'مخزن'), ('BRANCH', 'فرع'), ('QUARANTINE', 'حجر — تالف أو منتهٍ'), ('TRANSIT', 'قيد النقل')], db_index=True, default='WAREHOUSE', max_length=16, verbose_name='النوع')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('governorate', models.CharField(blank=True, max_length=100, verbose_name='المحافظة')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('is_default', models.BooleanField(default=False, help_text='يُستخدم حين لا يُحدَّد موقع صراحةً', verbose_name='الموقع الافتراضي')),
                ('is_sellable', models.BooleanField(default=True, help_text='مخزون الحجر لا يُباع منه', verbose_name='يُباع منه')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'موقع مخزني',
                'verbose_name_plural': 'المواقع المخزنية',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('is_default',), name='unique_default_stock_location')],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('reference', models.CharField(default=inventory.models.count_reference, max_length=32, unique=True, verbose_name='المرجع')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('IN_PROGRESS', 'جارٍ'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغى')], db_index=True, default='DRAFT', max_length=16, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بدأ في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='اكتمل في')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.stocklocation')),
            ],
            options={
                'verbose_name': 'جرد',
                'verbose_name_plural': 'عمليات الجرد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('number', models.CharField(db_index=True, default=inventory.models.batch_number, max_length=64, verbose_name='رقم الدفعة')),
                ('supplier_batch_number', models.CharField(blank=True, max_length=64, verbose_name='رقم دفعة المورّد')),
                ('quantity_received', models.PositiveIntegerField(verbose_name='الكمية المستلمة')),
                ('quantity_remaining', models.PositiveIntegerField(verbose_name='الكمية المتبقية')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='إلزامية — بدونها يستحيل حساب الربح لاحقًا', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تكلفة الوحدة')),
                ('manufactured_at', models.DateField(blank=True, null=True, verbose_name='تاريخ الإنتاج')),
                ('expires_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الصلاحية')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاستلام')),
                ('is_quarantined', models.BooleanField(default=False, help_text='لا تدخل في البيع', verbose_name='محجورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.product', verbose_name='المنتج')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.productvariant', verbose_name='النسخة')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.stocklocation', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['expires_at', 'received_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, default=inventory.models.movement_reference, max_length=32, verbose_name='المرجع')),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'استلام'), ('SALE', 'بيع'), ('RETURN_IN', 'مرتجع من عميل'), ('RETURN_OUT', 'مرتجع لمورّد'), ('TRANSFER_OUT', 'تحويل صادر'), ('TRANSFER_IN', 'تحويل وارد'), ('ADJUSTMENT_UP', 'تسوية بالزيادة'), ('ADJUSTMENT_DOWN', 'تسوية بالنقص'), ('DAMAGE', 'تلف'), ('EXPIRY', 'انتهاء صلاحية'), ('COUNT', 'تسوية جرد'), ('RESERVE', 'حجز'), ('RELEASE', 'إفراج عن حجز')], db_index=True, max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('balance_after', models.IntegerField(default=0, verbose_name='الرصيد بعد الحركة')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='لقطة وقت الحركة — تُستخدم في حساب COGS', max_digits=12, null=True, verbose_name='تكلفة الوحدة')),
                ('reference_type', models.CharField(blank=True, max_length=32, verbose_name='نوع المرجع')),
                ('reference_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف المرجع')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='الوقت')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.batch', verbose_name='الدفعة')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.stocklocation', verbose_name='الموقع')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='نفّذها')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product', verbose_name='المنتج')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('COMMITTED', 'مُنفَّذ'), ('RELEASED', 'مُفرَج عنه'), ('EXPIRED', 'منتهٍ')], db_index=True, default='ACTIVE', max_length=16, verbose_name='الحالة')),
                ('reference_type', models.CharField(blank=True, max_length=32, verbose_name='نوع المرجع')),
                ('reference_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف المرجع')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='ينتهي في')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحسم')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'حجز مخزون',
                'verbose_name_plural': 'حجوزات المخزون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('expected_quantity', models.IntegerField(verbose_name='الكمية المتوقعة')),
                ('counted_quantity', models.PositiveIntegerField(verbose_name='الكمية المعدودة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'سطر جرد',
                'verbose_name_plural': 'أسطر الجرد',
                'constraints': [models.UniqueConstraint(fields=('count', 'product', 'variant'), name='unique_count_line')],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'مخزون منخفض'), ('CRITICAL_STOCK', 'مخزون حرج'), ('OUT_OF_STOCK', 'نفاد'), ('EXPIRING_SOON', 'قرب انتهاء صلاحية'), ('EXPIRED', 'انتهت الصلاحية')], db_index=True, max_length=20, verbose_name='النوع')),
                ('current_value', models.IntegerField(default=0, verbose_name='القيمة الحالية')),
                ('threshold_value', models.IntegerField(default=0, verbose_name='قيمة الحد')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='محسوم')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحسم')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='catalog.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.stocklocation')),
            ],
            options={
                'verbose_name': 'تنبيه مخزون',
                'verbose_name_plural': 'تنبيهات المخزون',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_resolved', '-created_at'], name='inventory_s_is_reso_bca05b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_resolved', False)), fields=('alert_type', 'product', 'location'), name='unique_unresolved_alert')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('quantity_physical', models.PositiveIntegerField(default=0, verbose_name='الكمية الفعلية')),
                ('quantity_reserved', models.PositiveIntegerField(default=0, verbose_name='المحجوز')),
                ('quantity_damaged', models.PositiveIntegerField(default=0, verbose_name='التالف')),
                ('quantity_expired', models.PositiveIntegerField(default=0, verbose_name='المنتهي')),
                ('reorder_point', models.PositiveIntegerField(default=0, help_text='تنبيه حين ينزل المتاح عنه', verbose_name='حد إعادة الطلب')),
                ('critical_point', models.PositiveIntegerField(default=0, verbose_name='الحد الحرج')),
                ('last_counted_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر جرد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='catalog.product', verbose_name='المنتج')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='catalog.productvariant', verbose_name='النسخة')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='inventory.stocklocation', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'رصيد مخزون',
                'verbose_name_plural': 'أرصدة المخزون',
                'indexes': [models.Index(fields=['product', 'location'], name='inventory_s_product_5cabe4_idx'), models.Index(fields=['location', 'quantity_physical'], name='inventory_s_locatio_4c2e73_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'variant', 'location'), name='unique_stock_per_product_variant_location'), models.CheckConstraint(condition=models.Q(('quantity_reserved__lte', models.F('quantity_physical'))), name='reserved_never_exceeds_physical')],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product', 'location', 'expires_at'], name='inventory_b_product_4087b1_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expires_at', 'quantity_remaining'], name='inventory_b_expires_bf86b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_remaining__lte', models.F('quantity_received'))), name='batch_remaining_not_above_received'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'location', '-created_at'], name='inventory_s_product_63c4a3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_5aaa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['batch', '-created_at'], name='inventory_s_batch_i_ce6dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['status', 'expires_at'], name='inventory_s_status_c656ef_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_912c56_idx'),
        ),
    ]
