# Generated by Django 5.2 on 2026-08-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'حركة مخزون', 'verbose_name_plural': 'حركات المخزون'},
        ),
    ]
