# Generated by Django 5.2 on 2026-08-14 15:45

import core.models.base
import core.models.translatable
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pos.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_stockmovement_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('code', models.SlugField(default=pos.models.register_code, unique=True, verbose_name='رمز الجهاز')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
                ('location', models.ForeignKey(help_text='الجهاز يبيع من مخزون هذا الموقع وحده', on_delete=django.db.models.deletion.PROTECT, related_name='registers', to='inventory.stocklocation', verbose_name='الموقع المخزني')),
            ],
            options={
                'verbose_name': 'جهاز نقطة بيع',
                'verbose_name_plural': 'أجهزة نقطة البيع',
                'ordering': ['code'],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('number', models.CharField(db_index=True, default=pos.models.session_number, max_length=32, unique=True, verbose_name='رقم الوردية')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('CLOSED', 'مغلقة')], db_index=True, default='OPEN', max_length=8, verbose_name='الحالة')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='فُتحت في')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='أُغلقت في')),
                ('opening_float', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='النقد في الدرج عند فتح الوردية', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الرصيد الافتتاحي')),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, help_text='ما عدّه الكاشير فعليًا عند الإغلاق', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='النقد المعدود')),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='النقد المتوقَّع')),
                ('variance_note', models.TextField(blank=True, help_text='إلزامي حين يتجاوز الفرق الحد المضبوط', verbose_name='تفسير الفرق')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to=settings.AUTH_USER_MODEL, verbose_name='الكاشير')),
                ('closed_by', models.ForeignKey(blank=True, help_text='قد يكون مديرًا لا الكاشير نفسه', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أغلقها')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='pos.register', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'وردية',
                'verbose_name_plural': 'الورديات',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('kind', models.CharField(choices=[('SALE', 'بيع نقدي'), ('REFUND', 'مرتجع نقدي'), ('PAY_IN', 'إيداع في الدرج'), ('PAY_OUT', 'سحب من الدرج')], max_length=8, verbose_name='النوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='المبلغ')),
                ('reference_type', models.CharField(blank=True, max_length=32, verbose_name='نوع المرجع')),
                ('reference_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف المرجع')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='السبب')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='pos.possession')),
            ],
            options={
                'verbose_name': 'حركة صندوق',
                'verbose_name_plural': 'حركات الصندوق',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['session', '-created_at'], name='pos_cashmov_session_89a240_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['cashier', '-opened_at'], name='pos_possess_cashier_0943be_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['status', '-opened_at'], name='pos_possess_status_e05b36_idx'),
        ),
        migrations.AddConstraint(
            model_name='possession',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'OPEN')), fields=('register',), name='one_open_session_per_register'),
        ),
    ]
