"""Staff portal contracts — amounts as strings (ADR-31)."""

from rest_framework import serializers

from employees.models import CustomerAssignment, EmployeeProfile, EmployeeRole


class PermissionCodesField(serializers.Field):
    """
    The role's permissions in `app_label.codename` form.

    ⚠️  **By code, not by numeric id.**

        `auth.Permission` ids are generated by migration order and differ
        between development and production; a frontend that saves the number
        grants, in production, a permission other than the one the admin chose
        on their screen. The code is stable forever.

    ⚠️  And **only what is in the catalogue is accepted**.

        The table holds two hundred automatic permissions, `delete_user` among
        them; accepting any code means a hand-crafted call grants what the
        screen never displays.
    """

    def to_representation(self, value):
        return sorted(
            f"{p.content_type.app_label}.{p.codename}"
            for p in value.select_related("content_type")
        )

    def to_internal_value(self, data):
        from django.contrib.auth.models import Permission

        from core.permissions import CATALOGUE_CODES

        if not isinstance(data, list):
            raise serializers.ValidationError("القيمة يجب أن تكون قائمة")

        unknown = [code for code in data if code not in CATALOGUE_CODES]
        if unknown:
            raise serializers.ValidationError(
                f"صلاحيات خارج الدليل: {'، '.join(map(str, unknown))}"
            )

        found = []
        for code in dict.fromkeys(data):
            app_label, codename = code.split(".")
            permission = Permission.objects.filter(
                content_type__app_label=app_label, codename=codename
            ).first()
            if permission is None:
                raise serializers.ValidationError(f"صلاحية غير موجودة: {code}")
            found.append(permission)

        return found


class EmployeeRoleSerializer(serializers.ModelSerializer):
    permission_count = serializers.IntegerField(read_only=True, default=0)

    # ⚠️  `required=False` — creating a role with no permissions is a valid case:
    #     it is created empty and its permissions granted at leisure.
    permissions = PermissionCodesField(required=False)

    class Meta:
        model = EmployeeRole
        fields = [
            "id",
            "code",
            "kind",
            "name_ar",
            "name_en",
            "is_active",
            "permission_count",
            "permissions",
        ]
        read_only_fields = ["id", "permission_count"]


class EmployeeProfileSerializer(serializers.ModelSerializer):
    full_name = serializers.CharField(source="user.full_name", read_only=True)
    email = serializers.EmailField(source="user.email", read_only=True)
    role_name_ar = serializers.CharField(source="role.name_ar", read_only=True)
    role_name_en = serializers.CharField(source="role.name_en", read_only=True)
    manager_name = serializers.CharField(
        source="manager.user.full_name", read_only=True, default=None
    )
    customers_count = serializers.IntegerField(read_only=True, default=0)

    class Meta:
        model = EmployeeProfile
        fields = [
            "id",
            "employee_number",
            "full_name",
            "email",
            "role",
            "role_name_ar",
            "role_name_en",
            "manager",
            "manager_name",
            "phone_extension",
            "hired_on",
            "is_active",
            "customers_count",
        ]
        read_only_fields = ["id", "full_name", "email", "customers_count"]


class AssignedCustomerSerializer(serializers.Serializer):
    """
    An assigned customer — **a narrower payload than the admin sees**.

    ⚠️  The rep sees what serves their follow-up: name, phone, last order and
        total purchases. They do not see the internal notes, the tax number or
        the verification documents — those are review data, not sales data.
    """

    id = serializers.UUIDField(read_only=True)
    customer_number = serializers.CharField(read_only=True)
    display_name = serializers.CharField(read_only=True)
    phone = serializers.CharField(source="user.phone", read_only=True, default="")
    email = serializers.EmailField(source="user.email", read_only=True)
    segment = serializers.CharField(read_only=True)
    total_orders = serializers.IntegerField(read_only=True)
    total_spent = serializers.DecimalField(
        max_digits=12, decimal_places=2, coerce_to_string=True, read_only=True
    )
    last_order_at = serializers.DateTimeField(read_only=True)


class CustomerAssignmentSerializer(serializers.ModelSerializer):
    employee_number = serializers.CharField(source="employee.employee_number", read_only=True)
    employee_name = serializers.CharField(source="employee.user.full_name", read_only=True)
    customer_number = serializers.CharField(source="customer.customer_number", read_only=True)

    class Meta:
        model = CustomerAssignment
        fields = [
            "id",
            "customer",
            "customer_number",
            "employee",
            "employee_number",
            "employee_name",
            "status",
            "started_at",
            "ended_at",
            "note",
        ]
        read_only_fields = ["id", "status", "started_at", "ended_at"]


class AssignCustomerSerializer(serializers.Serializer):
    customer = serializers.UUIDField()
    employee = serializers.UUIDField()
    note = serializers.CharField(required=False, allow_blank=True, max_length=1000)


class EmployeeOrderLineSerializer(serializers.Serializer):
    """
    ⚠️  An **explicitly declared** line, not a `DictField`.

        `DictField` passed the id through as **text**, so it did not match the
        `in_bulk` keys, which are UUID objects — and every product was rejected
        as "not found" while it existed. Declaring it converts the type at the boundary.
    """

    product = serializers.UUIDField()
    quantity = serializers.IntegerField(min_value=1, max_value=9999)


class EmployeeOrderSerializer(serializers.Serializer):
    """
    ⚠️  **No amount fields** — the order is priced from the source.

        Accepting a total from the frontend means the rep sets their own selling
        price, which is the first thing exploited once commission is tied to sales.
    """

    customer = serializers.UUIDField()
    lines = EmployeeOrderLineSerializer(many=True, allow_empty=False)
    address_id = serializers.UUIDField(required=False, allow_null=True)
    address = serializers.DictField(required=False)
    shipping_method_code = serializers.CharField(max_length=50, required=False, allow_blank=True)
    payment_method = serializers.CharField(max_length=16)
    customer_note = serializers.CharField(required=False, allow_blank=True, max_length=1000)

    def validate(self, attrs):
        if not attrs.get("address_id") and not attrs.get("address"):
            raise serializers.ValidationError("أرسل `address_id` أو `address`")
        return attrs
