# Generated by Django 5.2 on 2026-08-12 17:45

import core.models.base
import customers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('customer_number', models.CharField(default=customers.models.customer_number, editable=False, help_text='للعرض والدعم الفني — ليس معرّف الرابط', max_length=24, unique=True, verbose_name='رقم العميل')),
                ('display_name_ar', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالعربية')),
                ('display_name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('segment', models.CharField(choices=[('NEW', 'جديد'), ('REGULAR', 'منتظم'), ('VIP', 'مميّز'), ('WHOLESALE', 'جملة'), ('INACTIVE', 'خامل')], db_index=True, default='NEW', max_length=16, verbose_name='التصنيف')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('tax_exempt', models.BooleanField(default=False, verbose_name='معفى من الضريبة')),
                ('commercial_register', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('accepts_marketing', models.BooleanField(default=False, verbose_name='يقبل الرسائل التسويقية')),
                ('notes', models.TextField(blank=True, help_text='لا يراها العميل', verbose_name='ملاحظات داخلية')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='عدد الطلبات')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المشتريات')),
                ('first_order_at', models.DateTimeField(blank=True, null=True, verbose_name='أول طلب')),
                ('last_order_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر طلب')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف عميل',
                'verbose_name_plural': 'ملفات العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('document_type', models.CharField(choices=[('NATIONAL_ID', 'بطاقة رقم قومي'), ('STUDENT_CARD', 'كارنيه جامعي'), ('MEDICAL_LICENSE', 'ترخيص مزاولة مهنة'), ('PHARMACY_LICENSE', 'ترخيص صيدلية'), ('TAX_CARD', 'بطاقة ضريبية'), ('COMMERCIAL_REGISTER', 'سجل تجاري')], max_length=32, verbose_name='نوع الوثيقة')),
                ('file', models.FileField(upload_to=customers.models.document_upload_to, verbose_name='الملف')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض')], db_index=True, default='PENDING', max_length=16, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='تنتهي في')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='راجعها')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customerprofile', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'وثيقة عميل',
                'verbose_name_plural': 'وثائق العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='التسمية')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='اسم المستلم')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('governorate', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('street', models.TextField(verbose_name='العنوان')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='رقم العقار')),
                ('landmark', models.CharField(blank=True, max_length=200, verbose_name='علامة مميزة')),
                ('is_default', models.BooleanField(default=False, verbose_name='العنوان الافتراضي')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customerprofile', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'عنوان عميل',
                'verbose_name_plural': 'عناوين العملاء',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['segment', '-created_at'], name='customers_c_segment_20dd6b_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['-last_order_at'], name='customers_c_last_or_6ba537_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdocument',
            index=models.Index(fields=['customer', 'document_type'], name='customers_c_custome_a892d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('customer',), name='unique_default_address_per_customer'),
        ),
    ]
