# Generated by Django 5.2 on 2026-08-12 22:36

import catalog.models
import core.models.base
import core.models.translatable
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='يُولَّد تلقائيًا ولا يتغيّر بعدها — تغييره يكسر الروابط', max_length=255, unique=True, verbose_name='المعرّف النصي')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='بلد المنشأ')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='رقم التسجيل')),
                ('website', models.URLField(blank=True, verbose_name='الموقع')),
                ('logo', models.ImageField(blank=True, upload_to=catalog.models.catalog_image_path, verbose_name='الشعار')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'شركة مصنّعة',
                'verbose_name_plural': 'الشركات المصنّعة',
                'ordering': ['name_ar'],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='يُولَّد تلقائيًا ولا يتغيّر بعدها — تغييره يكسر الروابط', max_length=255, unique=True, verbose_name='المعرّف النصي')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('image', models.ImageField(blank=True, upload_to=catalog.models.catalog_image_path, verbose_name='الصورة')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('path', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='المسار')),
                ('depth', models.PositiveSmallIntegerField(default=0, verbose_name='العمق')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='تظهر في القائمة')),
                ('meta_title_ar', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO عربي')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO إنجليزي')),
                ('meta_description_ar', models.CharField(blank=True, max_length=300, verbose_name='وصف SEO عربي')),
                ('meta_description_en', models.CharField(blank=True, max_length=300, verbose_name='وصف SEO إنجليزي')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name='الفئة الأب')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['path', 'display_order'],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='يُولَّد تلقائيًا ولا يتغيّر بعدها — تغييره يكسر الروابط', max_length=255, unique=True, verbose_name='المعرّف النصي')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('logo', models.ImageField(blank=True, upload_to=catalog.models.catalog_image_path, verbose_name='الشعار')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميّز')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='catalog.manufacturer', verbose_name='الشركة المصنّعة')),
            ],
            options={
                'verbose_name': 'براند',
                'verbose_name_plural': 'البراندات',
                'ordering': ['display_order', 'name_ar'],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='يُولَّد تلقائيًا ولا يتغيّر بعدها — تغييره يكسر الروابط', max_length=255, unique=True, verbose_name='المعرّف النصي')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='رمز المنتج')),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='EAN-13 أو UPC — يستخدمه ماسح نقطة البيع', max_length=64, verbose_name='الباركود')),
                ('kind', models.CharField(choices=[('SUPPLY', 'مستلزم طبي'), ('EQUIPMENT', 'جهاز أو معدة'), ('MEDICINE', 'دواء'), ('COSMETIC', 'مستحضر تجميلي'), ('SUPPLEMENT', 'مكمّل غذائي'), ('BOOK', 'كتاب أو مادة تعليمية'), ('APPAREL', 'ملابس طبية'), ('OTHER', 'أخرى')], db_index=True, default='SUPPLY', max_length=16, verbose_name='نوع المنتج')),
                ('short_description_ar', models.CharField(blank=True, max_length=300, verbose_name='وصف مختصر عربي')),
                ('short_description_en', models.CharField(blank=True, max_length=300, verbose_name='وصف مختصر إنجليزي')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, help_text='مرجع لمحرك التسعير — ليس السعر النهائي للعميل', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر المرجعي')),
                ('regulatory_class', models.CharField(choices=[('NOT_APPLICABLE', 'لا ينطبق'), ('OTC', 'يُصرف بدون وصفة'), ('PRESCRIPTION', 'يتطلب وصفة'), ('CONTROLLED', 'مادة خاضعة للرقابة')], db_index=True, default='NOT_APPLICABLE', max_length=20, verbose_name='التصنيف التنظيمي')),
                ('requires_prescription', models.BooleanField(db_index=True, default=False, help_text='خارج نطاق العمل الحالي — الحقل موجود لتجنّب هجرة لاحقة', verbose_name='يتطلب وصفة')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='رقم التسجيل')),
                ('active_ingredient_ar', models.CharField(blank=True, max_length=300, verbose_name='المادة الفعّالة عربي')),
                ('active_ingredient_en', models.CharField(blank=True, max_length=300, verbose_name='المادة الفعّالة إنجليزي')),
                ('strength', models.CharField(blank=True, help_text='مثال: 500mg', max_length=100, verbose_name='التركيز')),
                ('dosage_form', models.CharField(blank=True, choices=[('TABLET', 'أقراص'), ('CAPSULE', 'كبسولات'), ('SYRUP', 'شراب'), ('INJECTION', 'حقن'), ('CREAM', 'كريم'), ('OINTMENT', 'مرهم'), ('DROPS', 'قطرة'), ('SPRAY', 'بخاخ'), ('SUPPOSITORY', 'لبوس'), ('POWDER', 'بودرة'), ('OTHER', 'أخرى')], max_length=20, verbose_name='الشكل الدوائي')),
                ('pack_size', models.CharField(blank=True, help_text='مثال: 20 قرص', max_length=100, verbose_name='حجم العبوة')),
                ('storage_condition', models.CharField(choices=[('ROOM', 'حرارة الغرفة'), ('COOL', 'مكان بارد وجاف'), ('REFRIGERATED', 'مبرّد ٢-٨ °م'), ('FROZEN', 'مجمّد'), ('PROTECT_LIGHT', 'بعيدًا عن الضوء')], default='ROOM', max_length=20, verbose_name='شروط التخزين')),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='الوزن بالجرام')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='مميّز')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('meta_title_ar', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO عربي')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO إنجليزي')),
                ('meta_description_ar', models.CharField(blank=True, max_length=300, verbose_name='وصف SEO عربي')),
                ('meta_description_en', models.CharField(blank=True, max_length=300, verbose_name='وصف SEO إنجليزي')),
                ('access_policy', models.ForeignKey(blank=True, help_text='فارغ = السياسة الافتراضية', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='access.accesspolicy', verbose_name='سياسة الوصول')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='البراند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='الفئة')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.manufacturer', verbose_name='الشركة المصنّعة')),
                ('tax_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.taxclass', verbose_name='الفئة الضريبية')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('image', models.ImageField(upload_to=catalog.models.catalog_image_path, verbose_name='الصورة')),
                ('alt_text_ar', models.CharField(blank=True, max_length=200, verbose_name='النص البديل عربي')),
                ('alt_text_en', models.CharField(blank=True, max_length=200, verbose_name='النص البديل إنجليزي')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الصورة الرئيسية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['-is_primary', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='رمز النسخة')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='الباركود')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='الخصائص')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='يُضاف إلى السعر المرجعي للمنتج — قد يكون سالبًا', max_digits=12, verbose_name='فرق السعر')),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='الوزن بالجرام')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'نسخة منتج',
                'verbose_name_plural': 'نسخ المنتجات',
                'ordering': ['display_order', 'sku'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'display_order'], name='catalog_cat_parent__a3bae0_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'show_in_menu'], name='catalog_cat_is_acti_6aae28_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active', 'is_featured'], name='catalog_bra_is_acti_2dbfd6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='catalog_pro_is_acti_ed6a39_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='catalog_pro_brand_i_ca0f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['kind', 'is_active'], name='catalog_pro_kind_2b8693_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['access_policy', 'is_active'], name='catalog_pro_access__6dc87f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='catalog_pro_is_feat_b968c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_primary', True)), fields=('product',), name='unique_primary_image_per_product'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='catalog_pro_product_6c5ee9_idx'),
        ),
    ]
