# Generated by Django 5.2 on 2026-08-13 04:57

import core.models.base
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='لسلة الزائر قبل التسجيل', max_length=64, verbose_name='مفتاح الجلسة')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشطة'), ('CONVERTED', 'تحوّلت إلى طلب'), ('ABANDONED', 'مهجورة'), ('MERGED', 'دُمجت')], db_index=True, default='ACTIVE', max_length=16, verbose_name='الحالة')),
                ('coupon_code', models.CharField(blank=True, max_length=32, verbose_name='كود الكوبون')),
                ('shipping_method_code', models.CharField(blank=True, max_length=50, verbose_name='طريقة الشحن')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخر نشاط')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحويل')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سلة',
                'verbose_name_plural': 'السلال',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cart.cart', verbose_name='السلة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_lines', to='catalog.product', verbose_name='المنتج')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_lines', to='catalog.productvariant', verbose_name='النسخة')),
            ],
            options={
                'verbose_name': 'سطر سلة',
                'verbose_name_plural': 'أسطر السلال',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', '-last_activity_at'], name='cart_cart_status_da73e2_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key', 'status'], name='cart_cart_session_81d746_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'ACTIVE')), fields=('user',), name='unique_active_cart_per_user'),
        ),
        migrations.AddIndex(
            model_name='cartline',
            index=models.Index(fields=['cart', 'created_at'], name='cart_cartli_cart_id_ec0e01_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartline',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('cart', 'product', 'variant'), name='unique_cart_line'),
        ),
    ]
