# Generated by Django 5.2 on 2026-08-12 19:10

import core.models.base
import core.models.translatable
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('code', models.SlugField(unique=True, verbose_name='الرمز')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('level', models.CharField(choices=[('PUBLIC', 'عام'), ('REGISTERED', 'يتطلب تسجيل دخول'), ('RESTRICTED', 'مقيّد بأنواع حسابات'), ('PROFESSIONAL', 'مهنيون موثّقون فقط')], db_index=True, default='PUBLIC', max_length=16, verbose_name='المستوى')),
                ('allowed_account_types', models.JSONField(blank=True, default=list, help_text='قائمة فارغة = كل الأنواع (بحسب المستوى)', verbose_name='أنواع الحسابات المسموحة')),
                ('requires_verification', models.BooleanField(default=False, help_text='طبيب مسجّل ≠ طبيب موثّق', verbose_name='يتطلب توثيق الحساب')),
                ('required_permission', models.CharField(blank=True, help_text='بصيغة app_label.codename', max_length=100, verbose_name='صلاحية مطلوبة')),
                ('denial_message_ar', models.CharField(blank=True, max_length=300, verbose_name='رسالة المنع بالعربية')),
                ('denial_message_en', models.CharField(blank=True, max_length=300, verbose_name='رسالة المنع بالإنجليزية')),
                ('is_default', models.BooleanField(default=False, help_text='تُطبَّق على أي مورد بلا سياسة صريحة', verbose_name='السياسة الافتراضية')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'سياسة وصول',
                'verbose_name_plural': 'سياسات الوصول',
                'ordering': ['level', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('is_default',), name='unique_default_access_policy')],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
    ]
