# Generated by Django 5.2 on 2026-08-13 04:57

import core.models.base
import core.models.translatable
import django.core.validators
import django.db.models.deletion
import shipping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('number', models.CharField(default=shipping.models.shipment_number, max_length=32, unique=True, verbose_name='رقم الشحنة')),
                ('reference_type', models.CharField(blank=True, max_length=32, verbose_name='نوع المرجع')),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='معرّف المرجع')),
                ('status', models.CharField(choices=[('PENDING', 'قيد التجهيز'), ('PICKED', 'تم التجميع'), ('IN_TRANSIT', 'في الطريق'), ('OUT_FOR_DELIVERY', 'خرجت للتسليم'), ('DELIVERED', 'سُلّمت'), ('FAILED', 'فشل التسليم'), ('RETURNED', 'مرتجعة')], db_index=True, default='PENDING', max_length=20, verbose_name='الحالة')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='اسم المستلم')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='هاتف المستلم')),
                ('governorate', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('street', models.TextField(verbose_name='العنوان')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='رقم العقار')),
                ('landmark', models.CharField(blank=True, max_length=200, verbose_name='علامة مميزة')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='رسوم الشحن')),
                ('weight_grams', models.PositiveIntegerField(default=0, verbose_name='الوزن')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='شركة الشحن')),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='رقم التتبع')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الشحن')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('failure_reason', models.TextField(blank=True, verbose_name='سبب الفشل')),
            ],
            options={
                'verbose_name': 'شحنة',
                'verbose_name_plural': 'الشحنات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('code', models.SlugField(unique=True, verbose_name='الرمز')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('estimated_days_min', models.PositiveSmallIntegerField(default=1, verbose_name='أقل مدة بالأيام')),
                ('estimated_days_max', models.PositiveSmallIntegerField(default=3, verbose_name='أكثر مدة بالأيام')),
                ('is_pickup', models.BooleanField(default=False, help_text='بلا رسوم شحن وبلا عنوان', verbose_name='استلام من الفرع')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'طريقة شحن',
                'verbose_name_plural': 'طرق الشحن',
                'ordering': ['display_order', 'code'],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'قيد التجهيز'), ('PICKED', 'تم التجميع'), ('IN_TRANSIT', 'في الطريق'), ('OUT_FOR_DELIVERY', 'خرجت للتسليم'), ('DELIVERED', 'سُلّمت'), ('FAILED', 'فشل التسليم'), ('RETURNED', 'مرتجعة')], max_length=20, verbose_name='الحالة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment')),
            ],
            options={
                'verbose_name': 'حدث شحنة',
                'verbose_name_plural': 'أحداث الشحنات',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping.shippingmethod'),
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('code', models.SlugField(unique=True, verbose_name='الرمز')),
                ('governorates', models.JSONField(default=list, help_text='أسماء المحافظات المشمولة', verbose_name='المحافظات')),
                ('is_default', models.BooleanField(default=False, help_text='تُستخدم لأي محافظة غير مُسندة', verbose_name='الافتراضية')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'منطقة شحن',
                'verbose_name_plural': 'مناطق الشحن',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('is_default',), name='unique_default_shipping_zone')],
            },
            bases=(core.models.translatable.TranslatedFieldMixin, models.Model),
        ),
        migrations.AddField(
            model_name='shipment',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping.shippingzone'),
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الرسوم الأساسية')),
                ('free_above', models.DecimalField(blank=True, decimal_places=2, help_text='فارغ = لا شحن مجاني لهذه المنطقة', max_digits=12, null=True, verbose_name='مجاني فوق')),
                ('per_kg_fee', models.DecimalField(decimal_places=2, default=0, help_text='صفر = لا رسوم وزن', max_digits=12, verbose_name='رسوم الكيلوجرام')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone')),
            ],
            options={
                'verbose_name': 'تعريفة شحن',
                'verbose_name_plural': 'تعريفات الشحن',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('zone', 'method'), name='unique_rate_per_zone_method')],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', '-created_at'], name='shipping_sh_status_8a7968_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['reference_type', 'reference_id'], name='shipping_sh_referen_fa382a_idx'),
        ),
    ]
