# Generated by Django 5.2 on 2026-08-15 15:02

import core.models.base
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employeerole_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionScheme',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=120, verbose_name='الاسم بالإنجليزية')),
                ('base', models.CharField(choices=[('NET_SALES', 'صافي المبيعات'), ('GROSS_PROFIT', 'مجمل الربح')], default='NET_SALES', max_length=16, verbose_name='أساس الحساب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
            ],
            options={
                'verbose_name': 'خطة عمولة',
                'verbose_name_plural': 'خطط العمولة',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('from_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='من نسبة تحقيق ٪')),
                ('to_percent', models.DecimalField(blank=True, decimal_places=2, help_text='فارغ = بلا سقف', max_digits=5, null=True, verbose_name='إلى نسبة تحقيق ٪')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة العمولة ٪')),
            ],
            options={
                'verbose_name': 'شريحة عمولة',
                'verbose_name_plural': 'شرائح العمولة',
                'ordering': ['scheme', 'from_percent'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='عدد الطلبات')),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي المبيعات')),
                ('returns_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المرتجعات')),
                ('net_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='صافي المبيعات')),
                ('cost_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='تكلفة البضاعة')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مجمل الربح')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='قيمة الهدف')),
                ('achieved_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المُحقَّق')),
                ('achievement_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة التحقيق ٪')),
                ('base', models.CharField(choices=[('NET_SALES', 'صافي المبيعات'), ('GROSS_PROFIT', 'مجمل الربح')], max_length=16, verbose_name='أساس الحساب')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ الأساس')),
                ('tier_label', models.CharField(blank=True, max_length=64, verbose_name='الشريحة المطبَّقة')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة العمولة ٪')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مبلغ العمولة')),
                ('status', models.CharField(choices=[('CALCULATED', 'محسوبة'), ('APPROVED', 'معتمدة'), ('PAID', 'مصروفة'), ('REJECTED', 'مرفوضة')], db_index=True, default='CALCULATED', max_length=16, verbose_name='الحالة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الحساب')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commissions', to=settings.AUTH_USER_MODEL, verbose_name='المُعتمِد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='employees.employeeprofile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل عمولة',
                'verbose_name_plural': 'سجلات العمولة',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
