# Generated by Django 5.2 on 2026-08-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0001_initial'),
        ('employees', '0002_employeerole_group'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrecord',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='targets.monthlytarget', verbose_name='الهدف'),
        ),
        migrations.AddField(
            model_name='commissionscheme',
            name='role',
            field=models.ForeignKey(blank=True, help_text='فارغ = خطة عامة تُسنَد يدويًا', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_schemes', to='employees.employeerole', verbose_name='الدور'),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='commissions.commissionscheme', verbose_name='الخطة'),
        ),
        migrations.AddField(
            model_name='commissiontier',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='commissions.commissionscheme', verbose_name='الخطة'),
        ),
        migrations.AddIndex(
            model_name='commissionrecord',
            index=models.Index(fields=['year', 'month', 'status'], name='commissions_year_7a6e53_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee', 'year', 'month'), name='one_commission_per_employee_month'),
        ),
    ]
