# Generated by Django 5.2 on 2026-08-13 04:57

import core.models.base
import django.core.validators
import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0002_alter_stockmovement_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('number', models.CharField(db_index=True, default=orders.models.order_number, help_text='للعرض والدعم — ليس معرّف الرابط', max_length=32, unique=True, verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('CONFIRMED', 'مؤكد'), ('PROCESSING', 'قيد التجهيز'), ('SHIPPED', 'تم الشحن'), ('DELIVERED', 'تم التسليم'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغى'), ('REFUNDED', 'مسترد')], db_index=True, default='PENDING', max_length=16, verbose_name='الحالة')),
                ('payment_status', models.CharField(choices=[('UNPAID', 'غير مدفوع'), ('PENDING', 'قيد المعالجة'), ('PAID', 'مدفوع'), ('PARTIALLY_REFUNDED', 'مسترد جزئيًا'), ('REFUNDED', 'مسترد بالكامل'), ('FAILED', 'فشل')], db_index=True, default='UNPAID', max_length=20, verbose_name='حالة الدفع')),
                ('channel', models.CharField(choices=[('ONLINE', 'متجر إلكتروني'), ('POS', 'نقطة بيع'), ('EMPLOYEE', 'موظف'), ('PHONE', 'هاتف')], db_index=True, default='ONLINE', max_length=16, verbose_name='القناة')),
                ('currency', models.CharField(choices=[('EGP', 'جنيه مصري'), ('USD', 'دولار أمريكي'), ('EUR', 'يورو'), ('SAR', 'ريال سعودي'), ('AED', 'درهم إماراتي')], default='EGP', max_length=3, verbose_name='العملة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي قبل الخصم')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الخصم')),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خصم الكوبون')),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الضريبة')),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الشحن')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي النهائي')),
                ('coupon_code', models.CharField(blank=True, max_length=32, verbose_name='كود الكوبون')),
                ('shipping_method_code', models.CharField(blank=True, max_length=50, verbose_name='طريقة الشحن')),
                ('recipient_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المستلم')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف المستلم')),
                ('governorate', models.CharField(blank=True, max_length=100, verbose_name='المحافظة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('street', models.TextField(blank=True, verbose_name='العنوان')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='رقم العقار')),
                ('landmark', models.CharField(blank=True, max_length=200, verbose_name='علامة مميزة')),
                ('customer_note', models.TextField(blank=True, verbose_name='ملاحظة العميل')),
                ('internal_note', models.TextField(blank=True, verbose_name='ملاحظة داخلية')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('commission_employee', models.ForeignKey(blank=True, help_text='للمرحلة ١١ — قد يختلف عن المسؤول', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_commissioned', to=settings.AUTH_USER_MODEL, verbose_name='موظف العمولة')),
                ('created_by', models.ForeignKey(blank=True, help_text='الموظف أو الكاشير — فارغ للطلبات الإلكترونية', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customerprofile', verbose_name='العميل')),
                ('location', models.ForeignKey(blank=True, help_text='فرع نقطة البيع أو المخزن المُصرِّف', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.stocklocation', verbose_name='الموقع')),
                ('owner_employee', models.ForeignKey(blank=True, help_text='للمرحلة ١٠ — يُملأ لاحقًا', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_owned', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('product_sku', models.CharField(max_length=64, verbose_name='رمز المنتج')),
                ('product_name_ar', models.CharField(max_length=200, verbose_name='اسم المنتج بالعربية')),
                ('product_name_en', models.CharField(max_length=200, verbose_name='اسم المنتج بالإنجليزية')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('list_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='السعر المرجعي')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الخصم')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الضريبة')),
                ('tax_class_code', models.CharField(blank=True, max_length=50, verbose_name='رمز الفئة الضريبية')),
                ('price_list_code', models.CharField(blank=True, max_length=50, verbose_name='قائمة الأسعار')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='تكلفة الوحدة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.product', verbose_name='المنتج')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'سطر طلب',
                'verbose_name_plural': 'أسطر الطلبات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=16, verbose_name='من حالة')),
                ('to_status', models.CharField(max_length=16, verbose_name='إلى حالة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'تغيير حالة طلب',
                'verbose_name_plural': 'سجل حالات الطلبات',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='orders_orde_custome_413d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-created_at'], name='orders_orde_payment_8bdf8b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['channel', '-created_at'], name='orders_orde_channel_b885f9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['location', '-created_at'], name='orders_orde_locatio_80faf1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['owner_employee', '-created_at'], name='orders_orde_owner_e_4f5d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_3d73d3_idx'),
        ),
    ]
