# Generated by Django 5.2 on 2026-08-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='فارغ = بيعة كاونتر لعميل بلا حساب', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customerprofile', verbose_name='العميل'),
        ),
    ]
