# Generated by Django 4.2 on 2024-01-12 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderdetails_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_detail', to='orders.cart'),
        ),
    ]
