# Generated by Django 4.2 on 2024-01-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cartdetails_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetails',
            old_name='quatity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
