# Generated by Django 5.2 on 2026-08-13 13:07

import core.models.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('category', models.CharField(choices=[('ACCOUNT', 'الحساب'), ('ORDER', 'الطلبات'), ('PAYMENT', 'الدفع'), ('SHIPPING', 'الشحن'), ('INVENTORY', 'المخزون'), ('PROMOTION', 'العروض'), ('MARKETING', 'التسويق'), ('SYSTEM', 'النظام')], db_index=True, max_length=16, verbose_name='التصنيف')),
                ('priority', models.CharField(choices=[('LOW', 'منخفضة'), ('NORMAL', 'عادية'), ('HIGH', 'مرتفعة'), ('URGENT', 'عاجلة')], default='NORMAL', max_length=8, verbose_name='الأولوية')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='النص')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='رابط الإجراء')),
                ('reference_type', models.CharField(blank=True, max_length=32, verbose_name='نوع المرجع')),
                ('reference_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف المرجع')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['category', '-created_at'], name='notificatio_categor_6dc2ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('IN_APP', 'داخل التطبيق'), ('EMAIL', 'بريد إلكتروني'), ('SMS', 'رسالة نصية'), ('PUSH', 'إشعار فوري'), ('WHATSAPP', 'واتساب')], max_length=16, verbose_name='القناة')),
                ('category', models.CharField(choices=[('ACCOUNT', 'الحساب'), ('ORDER', 'الطلبات'), ('PAYMENT', 'الدفع'), ('SHIPPING', 'الشحن'), ('INVENTORY', 'المخزون'), ('PROMOTION', 'العروض'), ('MARKETING', 'التسويق'), ('SYSTEM', 'النظام')], max_length=16, verbose_name='التصنيف')),
                ('template_key', models.CharField(blank=True, max_length=100, verbose_name='مفتاح القالب')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name='المستلم')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الإرسال'), ('SENT', 'أُرسل'), ('FAILED', 'فشل'), ('SKIPPED', 'متخطّى — تفضيل المستخدم')], db_index=True, default='PENDING', max_length=16, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل إشعار',
                'verbose_name_plural': 'سجل الإشعارات',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_57d53d_idx'), models.Index(fields=['status', '-created_at'], name='notificatio_status_361e70_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=core.models.base.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف')),
                ('category', models.CharField(choices=[('ACCOUNT', 'الحساب'), ('ORDER', 'الطلبات'), ('PAYMENT', 'الدفع'), ('SHIPPING', 'الشحن'), ('INVENTORY', 'المخزون'), ('PROMOTION', 'العروض'), ('MARKETING', 'التسويق'), ('SYSTEM', 'النظام')], max_length=16, verbose_name='التصنيف')),
                ('channel', models.CharField(choices=[('IN_APP', 'داخل التطبيق'), ('EMAIL', 'بريد إلكتروني'), ('SMS', 'رسالة نصية'), ('PUSH', 'إشعار فوري'), ('WHATSAPP', 'واتساب')], max_length=16, verbose_name='القناة')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفضيل إشعار',
                'verbose_name_plural': 'تفضيلات الإشعارات',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'category', 'channel'), name='unique_notification_preference')],
            },
        ),
    ]
