# Generated by Django 4.2 on 2024-01-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_alter_brand_slug_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
